const promptHelp = {
  en: {
    promptHelpLabel: "How to get better cover concepts",
    promptHelpTitle: "How to get better cover concepts",
    promptHelpIntro:
      "You do not need to write a detailed art brief. Choose the audience and subject, then add a few optional words. Robot will develop several different, text-free cover-art directions automatically.",
    promptHelpIncludeTitle: "Useful optional keywords",
    promptHelpInclude: [
      "A central theme, such as communication, nature, discovery, or movement.",
      "Mood or energy, such as calm, playful, bold, or curious.",
      "Colours or materials, such as bright colours, paper, glass, or tactile shapes.",
      "When Visual treatment is Automatic, an alternate medium such as cartoon, illustration, or 3D.",
      "One thing that should be included or avoided, if it really matters.",
    ],
    promptHelpFocusTitle: "Keep it short:",
    promptHelpFocus:
      "A selected visual treatment overrides style keywords. With Automatic selected, a visual-medium keyword is a direct override; other keywords are soft guidance. The planner varies subjects, composition, viewpoint, lighting, and treatment details between concepts.",
    promptHelpExampleTitle: "Example keywords",
    promptHelpExample:
      "communication, bright colours, curious, tactile paper texture",
    promptHelpAvoidTitle: "Do not ask for",
    promptHelpAvoid:
      "titles, grade numbers, logos, labels, badges, captions, pseudo-writing, or a detailed list of objects. Typography is added later in InDesign.",
    promptHelpEnd:
      "Reference images are optional. They guide the general audience character, palette, and finish, but are not copied as layouts or templates.",
  },
  cs: {
    promptHelpLabel: "Jak získat lepší návrhy obálek",
    promptHelpTitle: "Jak získat lepší návrhy obálek",
    promptHelpIntro:
      "Nemusíte psát podrobné výtvarné zadání. Zvolte cílovou skupinu a předmět a případně přidejte několik klíčových slov. Robot sám připraví několik odlišných obrazových směrů obálky bez textu.",
    promptHelpIncludeTitle: "Užitečná volitelná klíčová slova",
    promptHelpInclude: [
      "Hlavní téma, například komunikace, příroda, objevování nebo pohyb.",
      "Nálada nebo energie, například klidná, hravá, výrazná nebo zvídavá.",
      "Barvy nebo materiály, například výrazné barvy, papír, sklo nebo hmatové tvary.",
      "Při automatickém výtvarném zpracování jiné médium, například kreslené, ilustrace nebo 3D.",
      "Jeden důležitý motiv, který má být použit nebo vynechán.",
    ],
    promptHelpFocusTitle: "Buďte struční:",
    promptHelpFocus:
      "Zvolené výtvarné zpracování má přednost před klíčovými slovy o stylu. Při automatické volbě je klíčové slovo určující médium přímý pokyn; ostatní slova jsou volná inspirace. Plánovač mezi koncepty mění motiv, kompozici, pohled, světlo a detaily zpracování.",
    promptHelpExampleTitle: "Příklad klíčových slov",
    promptHelpExample:
      "komunikace, výrazné barvy, zvídavé, hmatová textura papíru",
    promptHelpAvoidTitle: "Nezadávejte",
    promptHelpAvoid:
      "názvy, ročníky, loga, popisky, odznaky, titulky, napodobený text ani podrobný seznam předmětů. Typografie se doplní později v InDesignu.",
    promptHelpEnd:
      "Referenční obrázky jsou volitelné. Pomáhají určit obecný charakter pro cílovou skupinu, paletu a dokončení, ale nekopírují se jako rozvržení ani předloha.",
  },
} as const;

const subjects = {
  en: {
    preschoolGeneral: "Preschool / general learning",
    primaryGeneral: "Primary / general education",
    czechLanguage: "Czech language",
    literature: "Literature",
    foreignLanguage: "Foreign language",
    mathematics: "Mathematics",
    physics: "Physics",
    chemistry: "Chemistry",
    biology: "Biology / natural science",
    geography: "Geography",
    history: "History",
    civics: "Civics / social science",
    computing: "Computing / technology",
    vocational: "Vocational subject",
    examPreparation: "Exam preparation",
    other: "Other subject",
  },
  cs: {
    preschoolGeneral: "Mateřská škola / obecné učení",
    primaryGeneral: "1. stupeň ZŠ / obecné vzdělávání",
    czechLanguage: "Český jazyk",
    literature: "Literatura",
    foreignLanguage: "Cizí jazyk",
    mathematics: "Matematika",
    physics: "Fyzika",
    chemistry: "Chemie",
    biology: "Biologie / přírodopis",
    geography: "Zeměpis",
    history: "Dějepis",
    civics: "Občanská nauka / společenské vědy",
    computing: "Informatika / technologie",
    vocational: "Odborný předmět",
    examPreparation: "Příprava na zkoušky",
    other: "Jiný předmět",
  },
} as const;

export const coverUi = {
  en: {
    code: "IMAGE / COVER CONCEPTS",
    heading: "Cover Generator",
    active: "active sketches",
    selected: "direction selected",
    download: "DOWNLOAD ZIP ↓",
    exportArtboard: "EXPORT ARTBOARD ↓",
    artboardError: "No generated covers are visible in the viewport.",
    sketch: "SKETCH",
    choose: "↑ PREFERRED",
    upvote: "↑ USE AS PREFERENCE",
    reject: "Delete cover",
    empty:
      "Choose an audience and subject, then generate a first set of concepts. Keywords and reference images are optional.",
    generating: "GENERATING",
    references: "REFERENCE IMAGES",
    optional: "optional · 0–3",
    addCover: "ADD\nIMAGE",
    remove: "Remove",
    audience: "AUDIENCE",
    audiencePlaceholder: "Choose audience",
    audiencePreschool: "Preschool",
    audiencePrimary: "Primary school — grades 1–5",
    audienceLowerSecondary: "Lower secondary — grades 6–9",
    audienceUpperSecondary: "Upper-secondary school",
    style: "VISUAL TREATMENT",
    styleHelpLabel: "Preview visual treatments",
    styleHelpTitle: "Visual treatment examples",
    stylePromptLabel: "STYLE PROMPT",
    copyStylePrompt: "COPY STYLE PROMPT",
    stylePromptCopied: "COPIED",
    styleAutomatic: "Automatic — chosen for the subject",
    styleAtmosphericPhotomontage: "Atmospheric environmental photomontage",
    styleObjectMontage: "Tactile editorial object montage",
    styleScientificStudy: "Scientific macro / material study",
    styleIllustrationMontage: "Detailed stylized illustration montage",
    styleWoodEngraving: "Coloured wood engraving",
    styleRisograph: "Modern risograph",
    styleInkWatercolour: "Ink-lined watercolour",
    stylePropagandaWatercolour: "20th century-style propaganda watercolour",
    subject: "SUBJECT",
    subjectPlaceholder: "Choose subject",
    customSubject: "Custom subject",
    customSubjectPlaceholder: "Name the subject",
    keywords: "THEME OR KEYWORDS — OPTIONAL",
    keywordsPlaceholder: "communication, bright colours, curious",
    generateOne: "GENERATE 1",
    generateTwo: "GENERATE 2",
    generateFour: "GENERATE 4",
    generateSelectedOne: "GENERATE 1 WITH THIS PREFERENCE",
    generateSelectedTwo: "GENERATE 2 WITH THIS PREFERENCE",
    generateSelectedFour: "GENERATE 4 WITH THIS PREFERENCE",
    generatingCount: "GENERATING",
    note: "The planner turns a few inputs into distinct concepts with different focal ideas, viewpoints, compositions and visual treatments. Use a preferred concept as a broad direction, not an exact template.",
    close: "Close",
    zoom: "Zoom sketch",
    seedUnavailable: "seed unavailable",
    reportTitle: "Cover generation report",
    model: "IMAGE MODEL",
    previewOverlay: "TEXT OVERLAY PREVIEW",
    overlayBlack: "BLACK",
    overlayWhite: "WHITE",
    overlayNone: "None",
    overlayPreviewOnly:
      "ZIP downloads contain the original artwork. Artboard PDFs use the selected overlay colour.",

    modelFluxPro: "FLUX.2 Pro 1K",
    modelGemini: "Gemini Flash Lite 1K",

    modelFluxProNote: "Default 1K European FLUX model with seed control.",
    modelGeminiNote:
      "Alternative model with a different visual style; seed control is unavailable.",
    artOnly: "USE ART-FOCUSED REFERENCE CROPS",
    artOnlyHelp:
      "Ignore titles, grade labels, logos and other text by sending an art-focused crop directly to the image model.",
    referenceError: "A reference image could not be prepared.",
    limit:
      "Keep no more than 16 active sketches. Delete a few before generating more.",
    sketchError: "OpenRouter returned no cover sketches.",
    generationError: "Cover generation failed.",
    ...subjects.en,
    ...promptHelp.en,
  },
  cs: {
    code: "OBRAZ / NÁVRHY OBÁLEK",
    heading: "Generátor obálek",
    active: "aktivních návrhů",
    selected: "směr vybrán",
    download: "STÁHNOUT ZIP ↓",
    exportArtboard: "EXPORTOVAT PLOCHU ↓",
    artboardError:
      "V aktuálním výřezu nejsou viditelné žádné vygenerované obálky.",
    sketch: "NÁVRH",
    choose: "↑ PREFERENCE",
    upvote: "↑ POUŽÍT JAKO PREFERENCI",
    reject: "Smazat obálku",
    empty:
      "Zvolte cílovou skupinu a předmět a vygenerujte první sadu konceptů. Klíčová slova a referenční obrázky jsou volitelné.",
    generating: "GENERUJI",
    references: "REFERENČNÍ OBRÁZKY",
    optional: "volitelné · 0–3",
    addCover: "PŘIDAT\nOBRÁZEK",
    remove: "Odstranit",
    audience: "CÍLOVÁ SKUPINA",
    audiencePlaceholder: "Zvolte cílovou skupinu",
    audiencePreschool: "Mateřské školy",
    audiencePrimary: "1. stupeň ZŠ",
    audienceLowerSecondary: "2. stupeň ZŠ",
    audienceUpperSecondary: "Střední školy",
    style: "VÝTVARNÉ ZPRACOVÁNÍ",
    styleHelpLabel: "Ukázky výtvarného zpracování",
    styleHelpTitle: "Ukázky výtvarného zpracování",
    stylePromptLabel: "STYLOVÝ PROMPT",
    copyStylePrompt: "KOPÍROVAT STYLOVÝ PROMPT",
    stylePromptCopied: "ZKOPÍROVÁNO",
    styleAutomatic: "Automaticky — podle předmětu",
    styleAtmosphericPhotomontage: "Atmosférická environmentální fotomontáž",
    styleObjectMontage: "Taktilní redakční montáž objektů",
    styleScientificStudy: "Vědecká makro / materiálová studie",
    styleIllustrationMontage: "Montáž detailních stylizovaných ilustrací",
    styleWoodEngraving: "Barevný dřevoryt",
    styleRisograph: "Moderní risograf",
    styleInkWatercolour: "Akvarel s inkoustovou kresbou",
    stylePropagandaWatercolour: "Propagandistický akvarel ve stylu 20. století",
    subject: "PŘEDMĚT",
    subjectPlaceholder: "Zvolte předmět",
    customSubject: "Vlastní předmět",
    customSubjectPlaceholder: "Název předmětu",
    keywords: "TÉMA NEBO KLÍČOVÁ SLOVA — VOLITELNÉ",
    keywordsPlaceholder: "komunikace, výrazné barvy, zvídavost",
    generateOne: "VYGENEROVAT 1",
    generateTwo: "VYGENEROVAT 2",
    generateFour: "VYGENEROVAT 4",
    generateSelectedOne: "VYGENEROVAT 1 S TOUTO PREFERENCÍ",
    generateSelectedTwo: "VYGENEROVAT 2 S TOUTO PREFERENCÍ",
    generateSelectedFour: "VYGENEROVAT 4 S TOUTO PREFERENCÍ",
    generatingCount: "GENERUJI",
    note: "Plánovač převede několik vstupů na odlišné koncepty s různými hlavními motivy, pohledy, kompozicemi a výtvarným zpracováním. Preferovaný koncept slouží jako obecný směr, ne jako přesná předloha.",
    close: "Zavřít",
    zoom: "Zvětšit návrh",
    seedUnavailable: "seed není k dispozici",
    reportTitle: "Report generování obálky",
    model: "OBRAZOVÝ MODEL",
    previewOverlay: "NÁHLED TEXTU OBÁLKY",
    overlayBlack: "ČERNÝ",
    overlayWhite: "BÍLÝ",
    overlayNone: "Bez",
    overlayPreviewOnly:
      "ZIP obsahuje původní obraz. PDF exportní plochy používá zvolenou barvu překryvu.",

    modelFluxPro: "FLUX.2 Pro 1K",
    modelGemini: "Gemini Flash Lite 1K",

    modelFluxProNote:
      "Výchozí evropský model FLUX s 1K výstupem a podporou seedu.",
    modelGeminiNote:
      "Alternativní model s odlišným vizuálním stylem; seed nelze nastavit.",
    artOnly: "POUŽÍT VÝŘEZY ZAMĚŘENÉ NA OBRAZ",
    artOnlyHelp:
      "Ignorovat názvy, označení ročníků, loga a další text odesláním výřezu zaměřeného na obraz přímo obrazovému modelu.",
    referenceError: "Referenční obrázek se nepodařilo připravit.",
    limit:
      "Ponechte nejvýše 16 aktivních návrhů. Před dalším generováním některé smažte.",
    sketchError: "OpenRouter nevrátil žádné návrhy obálky.",
    generationError: "Generování obálky selhalo.",
    ...subjects.cs,
    ...promptHelp.cs,
  },
} as const;

export const localizedCoverUi = {
  en: { ...coverUi.en, exportArtboard: "EXPORT ARTBOARD PDF ↓" },
  cs: { ...coverUi.cs, exportArtboard: "EXPORTOVAT PLOCHU DO PDF ↓" },
} as const;
