export const mapProcessing = {
  en: [
    "unfolding a very large map",
    "looking for the tiny countries",
    "asking history what year it is",
    "checking whether the borders moved again",
    "putting the islands back",
    "consulting a suspiciously thick atlas",
    "straightening the coastlines",
    "negotiating with the label positions",
    "moving the legend out of the sea",
    "counting countries twice",
    "giving the SVG a final polish",
    "folding the map correctly on the first try",
  ],
  cs: [
    "rozkládání opravdu velké mapy",
    "hledání těch nejmenších států",
    "dotazování historie, jaký je právě rok",
    "kontrola, zda se hranice zase neposunuly",
    "vracení ostrovů na jejich místa",
    "listování podezřele tlustým atlasem",
    "narovnávání popisků",
    "stěhování legendy z moře",
    "dvojí počítání států",
    "závěrečné leštění SVG",
    "skládání mapy správně hned napoprvé",
  ],
} as const;

export const mapUi = {
  en: {
    subtitle:
      "Create source-backed SVG charts, diagrams, and factual maps. Specifications are validated and coordinates are rendered by code.",
    badge: "VERIFIED PIPELINE",
    preview: "SVG PREVIEW",
    empty: "Nothing scarier than an empty page.",
    timeline: "HISTORICAL BOUNDARY TIMELINE",
    negativeBce: "NEGATIVE = BCE",
    previousYear: "Previous year",
    nextYear: "Next year",
    mapYear: "Map year; use negative numbers for BCE",
    historicalTimeline: "Historical timeline",
    bce: "BCE",
    ce: "CE",
    layers: "LAYERS",
    mapLayers: {
      boundaries: "borders",
      labels: "country names",
      water: "seas and oceans",
      rivers: "rivers",
      climate: "climate zones",
      terrain: "terrain regions",
      mountains: "mountain ranges",
      cities: "cities and capitals",
      disputed: "disputed boundaries",
    },
    climateNote:
      "Köppen–Geiger zones represent 1980–2016 climate normals, independently of the selected political year.",
    climateLabels: ["Tropical", "Arid", "Temperate", "Cold", "Polar"],
    presentLayersNote:
      "These Natural Earth layers describe present-day geography and boundaries, independently of the selected historical year.",
    fillCountries: "FILL COUNTRIES",
    on: "ON",
    zoomIn: "Zoom +",
    zoomOut: "Zoom −",
    resetView: "Reset view",
    mapInstructions:
      "Drag to pan. Activate Fill countries before clicking territories. Changes are preserved in the downloaded SVG.",
    adobePalette: "ADOBE PALETTE",
    replacePalette: "Replace .ase",
    applyPalette: "Apply",
    shufflePalette: "Shuffle",
    importPalette: "Import .ase palette",
    editMap: "EDIT MAP WITH A PROMPT",
    mapPrompt: "For example: Fill NATO members blue and label the Baltic Sea.",
    downloadSvg: "Download SVG",
    warnings: "WARNINGS",
  },
  cs: {
    subtitle:
      "Vytváří zdrojované SVG grafy, schémata a faktické mapy. Specifikace ověří a souřadnice vykreslí kód.",
    badge: "OVĚŘOVANÝ POSTUP",
    preview: "NÁHLED SVG",
    empty: "Není nic děsivějšího než prázdná stránka.",
    timeline: "ČASOVÁ OSA HISTORICKÝCH HRANIC",
    negativeBce: "ZÁPORNÉ ČÍSLO = PŘ. N. L.",
    previousYear: "Předchozí rok",
    nextYear: "Následující rok",
    mapYear: "Rok mapy; pro období př. n. l. použijte záporné číslo",
    historicalTimeline: "Historická časová osa",
    bce: "PŘ. N. L.",
    ce: "N. L.",
    layers: "VRSTVY",
    mapLayers: {
      boundaries: "hranice",
      labels: "názvy států",
      water: "moře a oceány",
      rivers: "řeky",
      climate: "klimatická pásma",
      terrain: "oblasti reliéfu",
      mountains: "pohoří",
      cities: "města a hlavní města",
      disputed: "sporné hranice",
    },
    climateNote:
      "Pásma Köppenovy–Geigerovy klasifikace představují klimatické normály z let 1980–2016 bez ohledu na zvolený politický rok.",
    climateLabels: ["Tropické", "Suché", "Mírné", "Chladné", "Polární"],
    presentLayersNote:
      "Tyto vrstvy Natural Earth popisují současnou geografii a hranice bez ohledu na zvolený historický rok.",
    fillCountries: "VYBARVIT STÁTY",
    on: "ZAPNUTO",
    zoomIn: "Přiblížit +",
    zoomOut: "Oddálit −",
    resetView: "Obnovit pohled",
    mapInstructions:
      "Tažením mapu posunete. Před kliknutím na území zapněte Vybarvit státy. Změny se zachovají ve staženém SVG.",
    adobePalette: "PALETA ADOBE",
    replacePalette: "Nahradit .ase",
    applyPalette: "Použít",
    shufflePalette: "Promíchat",
    importPalette: "Importovat paletu .ase",
    editMap: "UPRAVIT MAPU PROMPTEM",
    mapPrompt: "Například: Vybarvi členy NATO modře a popiš Baltské moře.",
    downloadSvg: "Stáhnout SVG",
    warnings: "UPOZORNĚNÍ",
  },
} as const;
