export const solutionsImporterUi = {
  en: {
    heading: "Solutions Importer",
    subtitle: "Turn a clean PDF, the editor's annotated manuscript, and matching IDML into reviewable InDesign operations for text, tables, marks, and native colour fills.",
    local: "PROCESSED LOCALLY",
    clean: "CLEAN PDF",
    manuscript: "ANNOTATED MANUSCRIPT PDF",
    idml: "MATCHING CLEAN IDML",
    printersMarks: "One or both PDFs include printer's marks",
    printersMarksHelp: "Normalize both PDFs to their embedded TrimBox so bleed and print marks do not shift the InDesign coordinates.",
    printersMarksLog: "Printer-mark normalization enabled: using each PDF TrimBox as the InDesign page.",
    solutionTypography: "SOLUTION TYPOGRAPHY",
    solutionFont: "Font",
    solutionSize: "Size",
    choose: "Drop file here or choose",
    analyse: "Analyse chapter",
    analyseAgain: "Analyse again",
    analysing: "Analysing chapter…",
    processLog: "LOCAL PROCESS LOG",
    privacy: "Python, pdfplumber, and the IDML parser run inside this browser. The PDFs, IDML, annotations, and extracted text are never uploaded.",
    starting: "Starting local chapter analysis. No files will be uploaded.",
    failed: "Could not analyse the chapter files.",
    ready: "Analysis complete. Review uncertain operations before downloading the JSON.",
    error: "ERROR",
    pdfError: "Please choose a PDF file.",
    idmlError: "Please choose an IDML file.",
    reviewKicker: "IMPORT PLAN",
    reviewHeading: "Review detected solutions",
    downloadJson: "Download reviewed JSON",
    pages: "PAGES",
    textOperations: "TEXT",
    visualMarks: "MARKS",
    idmlTables: "TABLES",
    needsReview: "REVIEW",
    excluded: "EXCLUDED",
    reviewFilter: "Filter detected operations",
    filters: { all: "All", ready: "Ready", review: "Needs review" },
    pdfPage: "PDF page",
    bookPage: "book page",
    operations: "operations",
    reviewShort: "review",
    kinds: { text: "Text", cross: "Cross", circle: "Circle", color_mark: "Colour", note: "Note" },
    colour: "Colour family",
    positionedMark: "Positioned manuscript mark",
    reviewNote: "Likely source-text edits and notes are initially unticked. Re-enable any that are genuine answers; colour marks remain included but are flagged for visual review.",
    download: "DOWNLOAD FOR INDESIGN",
    simpleImporter: "Simple InDesign script",
    advancedImporter: "Advanced InDesign script",
    scriptChoice: "Start with Advanced for tables and aligned answer boxes. If it fails or places something incorrectly, run Simple: it only places the reviewed text at the PDF coordinates and is more failsafe.",
    need: "YOU WILL NEED",
    needs: ["Clean chapter PDF", "Annotated solutions manuscript PDF", "Clean IDML from the matching chapter", "A copy of the matching InDesign chapter"],
    warningTitle: "Run either importer on a copy.",
    warning: "Linked Illustrator and Photoshop artwork is reported for manual handling and is never modified.",
    steps: [
      ["Prepare three matching files", "Export the clean chapter PDF and IDML from the same InDesign file. Add the editor's annotated manuscript PDF with exactly the same pages and page order. If either PDF includes bleed or printer's marks, enable the checkbox above."],
      ["Analyse and review", "Choose the three files above and select the solution font and size. Robot separates added text from the clean PDF, reads PDF annotations, and inspects the IDML for page names, tables, styles, swatches, and linked artwork. Use the filters and checkboxes to remove false detections."],
      ["Download the operation JSON", "Download the reviewed JSON and keep it beside the matching chapter. It contains positioned operations and IDML metadata, not the source documents."],
      ["Install one or both scripts", "Download import_solutions_simple.jsx, import_solutions_advanced.jsx, or both. In InDesign choose Window → Utilities → Scripts, reveal the User scripts folder, and place the JSX files in Scripts Panel. Installation is needed only once."],
      ["Import and check", "Open a copy of the matching InDesign chapter and choose the reviewed JSON. Advanced maps answers into table cells and aligns answer frames. Simple places each answer directly at its PDF coordinates. If Advanced fails, undo it and try Simple."],
    ],
    checks: ["Check operations marked for review first.", "Check that each answer snapped to the intended box; unusually open layouts may not provide a detectable container.", "Check every duplicated table and resolved colour against the task's existing palette.", "Advanced replaces existing SOLUTIONS-layer page items after a successful import; always work on a versioned copy.", "One Undo removes a completed import."],
    trouble: "If it does not work",
    troubles: [
      ["Page count or names do not match", "Re-export the clean PDF and IDML from the same chapter, then make sure the manuscript contains those exact pages in the same order. Enable printer-mark normalization when a PDF page includes bleed or marks."],
      ["A grid was not filled", "Compact numeric grids are filled automatically. Large writing grids containing solution words or letters are intentionally left as ordinary text frames and marked with a nonprinting magenta review rectangle."],
      ["A colour is uncertain", "Annotation colour selects a hue family; the script chooses a nearby document swatch used in that task. Review the result when several similar swatches are available."],
      ["Artwork is not changed", "Linked AI, PSD, and raster artwork is intentionally left alone. Edit those few files manually and relink them in InDesign."],
    ],
  },
  cs: {
    heading: "Importér řešení",
    subtitle: "Převede čisté PDF, redakční rukopis s anotacemi a odpovídající IDML na kontrolovatelný plán pro texty, tabulky, značky a barevné výplně v InDesignu.",
    local: "ZPRACOVÁNO MÍSTNĚ",
    clean: "ČISTÉ PDF",
    manuscript: "ANOTOVANÝ RUKOPIS PDF",
    idml: "ODPOVÍDAJÍCÍ ČISTÉ IDML",
    printersMarks: "Jedno nebo obě PDF obsahují tiskové značky",
    printersMarksHelp: "Normalizuje obě PDF podle vloženého TrimBoxu, aby spadávka a tiskové značky neposunuly souřadnice v InDesignu.",
    printersMarksLog: "Normalizace tiskových značek je zapnutá: jako strana InDesignu se použije TrimBox každého PDF.",
    solutionTypography: "TYPOGRAFIE ŘEŠENÍ",
    solutionFont: "Písmo",
    solutionSize: "Velikost",
    choose: "Přetáhněte soubor nebo jej vyberte",
    analyse: "Analyzovat kapitolu",
    analyseAgain: "Analyzovat znovu",
    analysing: "Analyzuji kapitolu…",
    processLog: "MÍSTNÍ PROTOKOL ZPRACOVÁNÍ",
    privacy: "Python, pdfplumber a parser IDML běží v tomto prohlížeči. PDF, IDML, anotace ani extrahovaný text se nikam nenahrávají.",
    starting: "Spouštím místní analýzu kapitoly. Žádné soubory se nebudou nahrávat.",
    failed: "Soubory kapitoly se nepodařilo analyzovat.",
    ready: "Analýza je hotová. Před stažením JSON zkontrolujte nejisté operace.",
    error: "CHYBA",
    pdfError: "Vyberte soubor PDF.",
    idmlError: "Vyberte soubor IDML.",
    reviewKicker: "PLÁN IMPORTU",
    reviewHeading: "Kontrola nalezených řešení",
    downloadJson: "Stáhnout zkontrolovaný JSON",
    pages: "STRANY",
    textOperations: "TEXTY",
    visualMarks: "ZNAČKY",
    idmlTables: "TABULKY",
    needsReview: "KONTROLA",
    excluded: "VYŘAZENO",
    reviewFilter: "Filtrovat nalezené operace",
    filters: { all: "Vše", ready: "Připravené", review: "Ke kontrole" },
    pdfPage: "Strana PDF",
    bookPage: "strana knihy",
    operations: "operací",
    reviewShort: "ke kontrole",
    kinds: { text: "Text", cross: "Křížek", circle: "Kroužek", color_mark: "Barva", note: "Poznámka" },
    colour: "Barevná rodina",
    positionedMark: "Umístěná značka z rukopisu",
    reviewNote: "Pravděpodobné redakční změny textu a poznámky jsou zpočátku odškrtnuté. Skutečná řešení znovu povolte; barevné značky zůstávají zahrnuté, ale vyžadují vizuální kontrolu.",
    download: "STÁHNOUT PRO INDESIGN",
    simpleImporter: "Jednoduchý skript pro InDesign",
    advancedImporter: "Pokročilý skript pro InDesign",
    scriptChoice: "Začněte pokročilým skriptem pro tabulky a zarovnaná pole odpovědí. Pokud selže nebo něco umístí špatně, spusťte jednoduchý: pouze vloží zkontrolovaný text na souřadnice z PDF a je spolehlivější.",
    need: "BUDETE POTŘEBOVAT",
    needs: ["Čisté PDF kapitoly", "Anotovaný rukopis řešení v PDF", "Čisté IDML odpovídající kapitoly", "Kopii odpovídající kapitoly InDesignu"],
    warningTitle: "Kterýkoli importér spusťte na kopii.",
    warning: "Propojené soubory Illustratoru a Photoshopu se pouze uvedou ke kontrole a nikdy se automaticky nemění.",
    steps: [
      ["Připravte tři odpovídající soubory", "Čisté PDF kapitoly a IDML exportujte ze stejného souboru InDesignu. Přidejte redakční rukopis s přesně stejnými stranami a pořadím. Pokud některé PDF obsahuje spadávku nebo tiskové značky, zapněte volbu nahoře."],
      ["Analyzujte a zkontrolujte", "Vyberte tři soubory nahoře a zvolte písmo a velikost řešení. Robot oddělí přidaný text od čistého PDF, přečte anotace PDF a zkontroluje v IDML názvy stran, tabulky, styly, vzorník a propojenou grafiku. Filtry a zaškrtávátky odstraňte chybné nálezy."],
      ["Stáhněte JSON s operacemi", "Zkontrolovaný JSON uložte k odpovídající kapitole. Obsahuje umístěné operace a metadata IDML, nikoli zdrojové dokumenty."],
      ["Nainstalujte jeden nebo oba skripty", "Stáhněte import_solutions_simple.jsx, import_solutions_advanced.jsx nebo oba. V InDesignu zvolte Okna → Pomůcky → Skripty, otevřete uživatelskou složku skriptů a vložte soubory JSX do Scripts Panel. Instalaci stačí provést jednou."],
      ["Importujte a zkontrolujte", "Otevřete kopii odpovídající kapitoly a vyberte zkontrolovaný JSON. Pokročilý skript vkládá odpovědi do buněk tabulek a zarovnává textová pole. Jednoduchý vloží každou odpověď přímo na souřadnice z PDF. Pokud pokročilý selže, vraťte krok zpět a zkuste jednoduchý."],
    ],
    checks: ["Nejdříve projděte operace označené ke kontrole.", "Ověřte, že každé řešení zapadlo do správného pole; ve velmi otevřeném layoutu nemusí být kontejner rozpoznatelný.", "Zkontrolujte každou duplikovanou tabulku a zvolenou barvu podle palety úlohy.", "Pokročilý skript po úspěšném importu nahradí stávající objekty ve vrstvě SOLUTIONS; vždy pracujte s verzovanou kopií.", "Jeden krok Zpět odstraní celý dokončený import."],
    trouble: "Když něco nefunguje",
    troubles: [
      ["Nesouhlasí počet nebo názvy stran", "Čisté PDF a IDML znovu exportujte ze stejné kapitoly a ověřte, že rukopis obsahuje přesně stejné strany ve stejném pořadí. Pokud PDF obsahuje spadávku nebo značky, zapněte normalizaci tiskových značek."],
      ["Mřížka se nevyplnila", "Kompaktní číselné mřížky se vyplňují automaticky. Velké psací mřížky, jejichž řešení obsahuje slova nebo písmena, záměrně zůstanou jako běžné textové rámečky a označí se netisknutelným purpurovým kontrolním obdélníkem."],
      ["Barva není jistá", "Barva anotace určuje barevnou rodinu; skript vybere blízký vzorek dokumentu použitý v dané úloze. Když je podobných vzorků více, výsledek zkontrolujte."],
      ["Grafika se nezměnila", "Propojené AI, PSD a rastrové soubory se záměrně nemění. Těchto několik souborů upravte ručně a v InDesignu je znovu propojte."],
    ],
  },
} as const;
