export const typesetterUi = {
  en: {
    code: "DESIGN / TYPESETTER",
    heading: "Typesetter",
    intro:
      "Turn an unstructured Word manuscript into reviewed semantic JSON for an existing InDesign template.",
    steps: [
      "Files",
      "Inventory",
      "Roles",
      "Mapping",
      "Analysis",
      "Review",
      "Export",
    ],
    manuscript: "WORD MANUSCRIPT",
    template: "INDESIGN TEMPLATE",
    chooseDocx: "Drop a DOCX here or choose",
    chooseIdml: "Drop an IDML here or choose",
    inspect: "Inspect files locally",
    inspecting: "Inspecting files…",
    inspectAgain: "Inspect again",
    localLog: "LOCAL EXTRACTION LOG",
    localPrivacy:
      "The DOCX and IDML packages are opened locally in this browser. Only extracted manuscript blocks are sent to the selected AI model after you start an AI step.",
    docxError: "Choose a .docx Word document.",
    idmlError: "Choose an .idml InDesign template.",
    inventory: "Template inventory",
    manuscriptBlocks: "MANUSCRIPT BLOCKS",
    paragraphStyles: "PARAGRAPH STYLES",
    objectStyles: "OBJECT STYLES",
    labels: "SCRIPT LABELS",
    layers: "LAYERS",
    warnings: "Preflight warnings",
    requiredLabelFound: "Main-story label found",
    requiredLabelMissing: "Main-story label missing",
    prescan: "Ask AI to suggest roles",
    prescanning: "Scanning manuscript…",
    prescanAgain: "Scan again",
    prescanPrivacy:
      "The pre-scan receives a representative sample of extracted manuscript blocks and the controlled role catalogue. It never receives the IDML file.",
    suggestions: "Semantic role suggestions",
    suggestionsIntro:
      "Accept the roles this publication uses. Add or remove roles before mapping them to the template.",
    suggested: "AI SUGGESTED",
    roleExamples: "Manuscript examples",
    noExamples: "No example supplied",
    mapping: "Role-to-style mapping",
    mappingIntro:
      "Style names come directly from the uploaded IDML. Raw style names cannot be typed.",
    semanticRole: "Semantic role",
    paragraphStyle: "Paragraph style",
    objectStyle: "Object style",
    optional: "Optional",
    chooseStyle: "Choose a style…",
    templateIdentity: "Template identity",
    templateId: "Template ID",
    templateVersion: "Version",
    mappingReady: "Mapping is valid",
    mappingIncomplete: "Complete every active role mapping",
    analyse: "Classify the complete manuscript",
    analysing: "Classifying manuscript…",
    analyseAgain: "Analyse again",
    aiLog: "AI ANALYSIS LOG",
    review: "Review manuscript blocks",
    reviewKicker: "TYPESETTING PLAN",
    reviewHeading: "Typesetter Report",
    filter: "Filter blocks",
    filters: {
      all: "All",
      review: "Needs review",
      images: "Images",
      unsupported: "Unsupported",
    },
    confidence: "confidence",
    sourceKind: "Source",
    confirm: "Confirm",
    confirmed: "Confirmed",
    imagePrompt: "Image prompt",
    unresolved: "UNRESOLVED",
    images: "IMAGE REQUESTS",
    unsupported: "UNSUPPORTED",
    total: "BLOCKS",
    roles: "ROLES",
    exportHeading: "Export for InDesign",
    exportIntro:
      "Download the reviewed JSON and run the importer on a copy of the matching InDesign template.",
    downloadJson: "Download reviewed JSON",
    importer: "Typesetter InDesign script",
    download: "DOWNLOAD FOR INDESIGN",
    need: "YOU WILL NEED",
    needs: [
      "Reviewed Typesetter JSON",
      "A copy of the matching InDesign template",
      "The first main-story frame labelled typesetter:story:main",
    ],
    exportBlocked:
      "Resolve all review items and mapping errors before downloading JSON.",
    setup: "Template setup and import guide",
    workflowProgress: "WORKFLOW PROGRESS",
    stepComplete: "Complete",
    stepCurrent: "Current step",
    stepUpcoming: "Not started",
    setupSteps: [
      [
        "Prepare the main story",
        "Create and thread the main text frames. Select the first frame and enter typesetter:story:main in Window → Utilities → Script Label.",
      ],
      [
        "Prepare styles",
        "Create the paragraph styles needed by this publication. Optionally create an object style for image-request frames, then export the template as IDML.",
      ],
      [
        "Map and review",
        "Upload the DOCX and IDML, accept semantic roles, map each role to a real template style, and review every uncertain block.",
      ],
      [
        "Import on a copy",
        "Open a copy of the matching InDesign file, run import_typesetter.jsx, select the reviewed JSON, and inspect all pages and overset text.",
      ],
    ],
    imageNote:
      "Image requests are ordinary, unanchored frames on the IMAGE REQUESTS layer. They appear on the pasteboard beside the relevant text flow and must be positioned or replaced manually.",
    failed: "Typesetter could not complete this step.",
    noSuggestions: "The model returned no usable role suggestions.",
    invalidResponse: "The model returned an invalid manuscript classification.",
    batch: (current: number, total: number) =>
      `Analysing batch ${current}/${total}`,
  },
  cs: {
    code: "DESIGN / SAZEČ",
    heading: "Sazeč",
    intro:
      "Převede nestrukturovaný rukopis ve Wordu na zkontrolovaný sémantický JSON pro existující šablonu InDesignu.",
    steps: [
      "Soubory",
      "Inventář",
      "Role",
      "Mapování",
      "Analýza",
      "Kontrola",
      "Export",
    ],
    manuscript: "RUKOPIS WORD",
    template: "ŠABLONA INDESIGNU",
    chooseDocx: "Přetáhněte DOCX nebo jej vyberte",
    chooseIdml: "Přetáhněte IDML nebo jej vyberte",
    inspect: "Zkontrolovat soubory místně",
    inspecting: "Kontroluji soubory…",
    inspectAgain: "Zkontrolovat znovu",
    localLog: "PROTOKOL MÍSTNÍ EXTRAKCE",
    localPrivacy:
      "Balíčky DOCX a IDML se otevírají místně v tomto prohlížeči. Vybranému modelu AI se odešlou pouze extrahované bloky rukopisu, až spustíte krok AI.",
    docxError: "Vyberte dokument Word ve formátu .docx.",
    idmlError: "Vyberte šablonu InDesignu ve formátu .idml.",
    inventory: "Inventář šablony",
    manuscriptBlocks: "BLOKY RUKOPISU",
    paragraphStyles: "ODSTAVCOVÉ STYLY",
    objectStyles: "OBJEKTOVÉ STYLY",
    labels: "POPISKY SKRIPTU",
    layers: "VRSTVY",
    warnings: "Upozornění před kontrolou",
    requiredLabelFound: "Popisek hlavního článku nalezen",
    requiredLabelMissing: "Popisek hlavního článku chybí",
    prescan: "Nechat AI navrhnout role",
    prescanning: "Procházím rukopis…",
    prescanAgain: "Projít znovu",
    prescanPrivacy:
      "Předběžná analýza obdrží reprezentativní vzorek extrahovaných bloků a řízený katalog rolí. Soubor IDML nikdy neobdrží.",
    suggestions: "Návrhy sémantických rolí",
    suggestionsIntro:
      "Potvrďte role používané v této publikaci. Před mapováním do šablony můžete role přidat nebo odebrat.",
    suggested: "NAVRŽENO AI",
    roleExamples: "Příklady z rukopisu",
    noExamples: "Nebyl dodán příklad",
    mapping: "Mapování rolí na styly",
    mappingIntro:
      "Názvy stylů pocházejí přímo z nahraného IDML. Vlastní názvy nelze zadávat ručně.",
    semanticRole: "Sémantická role",
    paragraphStyle: "Odstavcový styl",
    objectStyle: "Objektový styl",
    optional: "Volitelné",
    chooseStyle: "Vyberte styl…",
    templateIdentity: "Identita šablony",
    templateId: "ID šablony",
    templateVersion: "Verze",
    mappingReady: "Mapování je platné",
    mappingIncomplete: "Dokončete mapování všech aktivních rolí",
    analyse: "Klasifikovat celý rukopis",
    analysing: "Klasifikuji rukopis…",
    analyseAgain: "Analyzovat znovu",
    aiLog: "PROTOKOL ANALÝZY AI",
    review: "Kontrola bloků rukopisu",
    reviewKicker: "PLÁN SAZBY",
    reviewHeading: "Přehled Sazeče",
    filter: "Filtrovat bloky",
    filters: {
      all: "Vše",
      review: "Ke kontrole",
      images: "Obrázky",
      unsupported: "Nepodporované",
    },
    confidence: "jistota",
    sourceKind: "Zdroj",
    confirm: "Potvrdit",
    confirmed: "Potvrzeno",
    imagePrompt: "Prompt obrázku",
    unresolved: "NEVYŘEŠENO",
    images: "POŽADAVKY NA OBRÁZKY",
    unsupported: "NEPODPOROVÁNO",
    total: "BLOKY",
    roles: "ROLE",
    exportHeading: "Export pro InDesign",
    exportIntro:
      "Stáhněte zkontrolovaný JSON a spusťte importér na kopii odpovídající šablony InDesignu.",
    downloadJson: "Stáhnout zkontrolovaný JSON",
    importer: "Skript Sazeče pro InDesign",
    download: "STÁHNOUT PRO INDESIGN",
    need: "BUDETE POTŘEBOVAT",
    needs: [
      "Zkontrolovaný JSON ze Sazeče",
      "Kopii odpovídající šablony InDesignu",
      "První rámeček hlavního článku označený typesetter:story:main",
    ],
    exportBlocked:
      "Před stažením JSON vyřešte všechny položky ke kontrole a chyby mapování.",
    setup: "Příprava šablony a návod k importu",
    workflowProgress: "PRŮBĚH PRÁCE",
    stepComplete: "Hotovo",
    stepCurrent: "Aktuální krok",
    stepUpcoming: "Zatím nezačalo",
    setupSteps: [
      [
        "Připravte hlavní článek",
        "Vytvořte a zřetězte hlavní textové rámečky. Vyberte první rámeček a v Okna → Pomůcky → Popisek skriptu zadejte typesetter:story:main.",
      ],
      [
        "Připravte styly",
        "Vytvořte odstavcové styly potřebné pro publikaci. Volitelně vytvořte objektový styl rámečků požadavků na obrázky a potom šablonu exportujte jako IDML.",
      ],
      [
        "Mapujte a kontrolujte",
        "Nahrajte DOCX a IDML, potvrďte sémantické role, každou roli namapujte na skutečný styl šablony a zkontrolujte všechny nejisté bloky.",
      ],
      [
        "Importujte do kopie",
        "Otevřete kopii odpovídajícího souboru InDesignu, spusťte import_typesetter.jsx, vyberte zkontrolovaný JSON a zkontrolujte všechny strany i přetečený text.",
      ],
    ],
    imageNote:
      "Požadavky na obrázky jsou běžné neukotvené rámečky ve vrstvě IMAGE REQUESTS. Objeví se na pracovní ploše vedle souvisejícího toku textu a je nutné je ručně umístit nebo nahradit.",
    failed: "Sazeči se nepodařilo dokončit tento krok.",
    noSuggestions: "Model nevrátil žádné použitelné návrhy rolí.",
    invalidResponse: "Model vrátil neplatnou klasifikaci rukopisu.",
    batch: (current: number, total: number) =>
      `Analyzuji dávku ${current}/${total}`,
  },
} as const;
