import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../../../../../", import.meta.url);

test("registers one Solutions Importer with one v2 extraction flow", async () => {
  const [workspace, registry, component] = await Promise.all([
    readFile(new URL("app/Workspace.tsx", root), "utf8"),
    readFile(new URL("app/_tools/registry.ts", root), "utf8"),
    readFile(
      new URL("app/_tools/design/solutions-importer/MainInterface.tsx", root),
      "utf8",
    ),
  ]);

  assert.match(workspace, /selected === "solutions"/);
  assert.match(
    workspace,
    /<SolutionsImporterMainInterface language=\{language\}/,
  );
  assert.doesNotMatch(workspace, /solutionsBeta|SolutionsBeta|SolutionsAlpha/);
  assert.equal((registry.match(/id: "solutions"/g) || []).length, 1);
  assert.match(registry, /folder: "design\/solutions-importer"/);
  assert.match(component, /indesign-solutions-v2/);
  assert.match(component, /\/solutions\/pyodide-worker\.js/);
});

test("ships one extractor and one mode-selecting InDesign importer", async () => {
  const [extractor, worker, importer, simple, advanced, component] =
    await Promise.all([
      readFile(
        new URL(
          "app/_tools/design/solutions-importer/public/extract_solution_operations.py",
          root,
        ),
        "utf8",
      ),
      readFile(
        new URL(
          "app/_tools/design/solutions-importer/public/pyodide-worker.js",
          root,
        ),
        "utf8",
      ),
      readFile(
        new URL(
          "app/_tools/design/solutions-importer/public/import_solutions.jsx",
          root,
        ),
        "utf8",
      ),
      readFile(
        new URL(
          "app/_tools/design/solutions-importer/public/import_solutions_simple.jsx",
          root,
        ),
        "utf8",
      ),
      readFile(
        new URL(
          "app/_tools/design/solutions-importer/public/import_solutions_advanced.jsx",
          root,
        ),
        "utf8",
      ),
      readFile(
        new URL("app/_tools/design/solutions-importer/MainInterface.tsx", root),
        "utf8",
      ),
    ]);

  assert.match(extractor, /indesign-solutions-v2/);
  assert.match(extractor, /matching_page_geometries/);
  assert.match(extractor, /TrimBox/);
  assert.match(worker, /extract_solution_operations\.py/);
  assert.match(worker, /\/solutions\/extract_solution_operations\.py/);
  for (const script of [importer, simple, advanced]) {
    assert.match(script, /LAYER_NAME = "SOLUTIONS"/);
    assert.match(script, /TEXT_STYLE_NAME = "Solutions"/);
    assert.match(script, /indesign-solutions-v2/);
    assert.match(script, /Noto Sans/);
  }
  assert.match(importer, /function chooseImportMode/);
  assert.match(importer, /__SOLUTIONS_IMPORT_MODE__/);
  assert.match(importer, /function runSimpleImport/);
  assert.match(importer, /CELL_STYLE_NAME = "Cell Solutions"/);
  assert.match(importer, /collectAnswerBoxes/);
  assert.match(importer, /locateGridPlacement/);
  assert.match(importer, /function expandOperationGlyphs/);
  assert.match(importer, /getTableCopy/);
  assert.match(importer, /createContinuationFrame/);
  assert.match(
    importer,
    /Advanced replaces every existing item on the SOLUTIONS layer/,
  );
  assert.match(
    importer,
    /Simple replaces only frames generated by an earlier Simple import/,
  );

  assert.match(simple, /failsafe importer/);
  assert.doesNotMatch(simple, /locateGridPlacement|getTableCopy/);
  assert.match(advanced, /locateGridPlacement/);

  assert.match(component, /\/solutions\/import_solutions\.jsx/);
  assert.doesNotMatch(
    component,
    /href="\/solutions\/import_solutions_(?:simple|advanced)\.jsx"/,
  );
  assert.match(component, /scriptChoice/);
});

test("keeps the completed Solutions report compact by default", async () => {
  const [component, copy, styles] = await Promise.all([
    readFile(
      new URL("app/_tools/design/solutions-importer/MainInterface.tsx", root),
      "utf8",
    ),
    readFile(
      new URL("app/_tools/design/solutions-importer/copy.ts", root),
      "utf8",
    ),
    readFile(new URL("app/globals.css", root), "utf8"),
  ]);

  assert.match(
    component,
    /\[reviewExpanded, setReviewExpanded\] = useState\(false\)/,
  );
  assert.match(component, /aria-expanded=\{reviewExpanded\}/);
  assert.match(component, /aria-controls="solutions-report-details"/);
  assert.match(component, /<h2 className="solutions-detail-review-heading">/);

  const reportStart = component.indexOf("solutions-detail-review-head");
  const statsStart = component.indexOf("solutions-detail-stats", reportStart);
  const detailsStart = component.indexOf("{reviewExpanded &&", reportStart);
  const filterStart = component.indexOf("solutions-detail-filter", reportStart);
  const pagesStart = component.indexOf("solutions-detail-pages", reportStart);
  assert.ok(reportStart < statsStart && statsStart < detailsStart);
  assert.ok(detailsStart < filterStart && detailsStart < pagesStart);

  assert.match(
    component,
    /solutionPreviewFont = solutionFont === "Times New Roman" \? solutionFont : "Arial"/,
  );
  assert.match(component, /`\$\{sourceName\}_Solutions\.json`/);
  assert.match(
    component,
    /solutions-create\$\{analysisComplete \? " is-complete"/,
  );
  assert.match(
    component,
    /solutions-progress\$\{analysisComplete \? " is-complete"/,
  );
  assert.match(copy, /reviewHeading: "Solutions Report"/);
  assert.match(copy, /downloadJson: "Download JSON"/);
  assert.match(copy, /reviewHeading: "Přehled řešení"/);
  assert.match(copy, /downloadJson: "Stáhnout JSON"/);
  assert.match(
    styles,
    /solutions-console\s*\{\s*display:\s*flex;\s*max-height:\s*190px/,
  );
  assert.match(
    styles,
    /solutions-create\.is-complete\s*\{\s*background:\s*var\(--teal\)/,
  );
  assert.match(
    styles,
    /solutions-progress\.is-complete \.solutions-console\s*\{\s*max-height:\s*95px/,
  );
});

test("Advanced importer expands grouped PDF text into grid-cell tokens", async () => {
  const advanced = await readFile(
    new URL(
      "app/_tools/design/solutions-importer/public/import_solutions_advanced.jsx",
      root,
    ),
    "utf8",
  );
  const blockStart = advanced.indexOf("function parseGridPrefix");
  const blockEnd = advanced.indexOf("function isQuestionLine", blockStart);
  assert.notEqual(blockStart, -1);
  assert.notEqual(blockEnd, -1);

  const parseGridPrefix = Function(
    `${advanced.slice(blockStart, blockEnd)}; return parseGridPrefix;`,
  )();
  const groupedGlyph = (text) => ({
    text,
    bounds: [100, 20, 112, 20 + text.length * 8],
  });

  assert.equal(
    parseGridPrefix({ glyphs: [groupedGlyph("92 - 75 = 17")] })
      .glyphs.map((glyph) => glyph.text)
      .join(""),
    "92-75=17",
  );
  assert.equal(
    parseGridPrefix({ glyphs: [groupedGlyph("× ÷ ± ≤ ≥ ≠ /")] })
      .glyphs.map((glyph) => glyph.text)
      .join(""),
    "×÷±≤≥≠/",
  );
  assert.deepEqual(
    parseGridPrefix({ glyphs: [groupedGlyph("multe")] }).glyphs,
    [],
  );
  assert.equal(
    parseGridPrefix({ glyphs: [groupedGlyph("A")] }).glyphs[0].text,
    "A",
  );
  assert.deepEqual(
    parseGridPrefix({ glyphs: [groupedGlyph("AB")] }).glyphs,
    [],
  );
  assert.equal(
    parseGridPrefix({
      glyphs: [
        { text: "A", bounds: [100, 20, 112, 28] },
        { text: "B", bounds: [100, 36, 112, 44] },
      ],
    })
      .glyphs.map((glyph) => glyph.text)
      .join(""),
    "AB",
  );
});
