export const copy = {
  en: {
    prompt: "Let’s go!",
    text: "Text",
    image: "Image",
    design: "Design",
    apps: {
      extraction: "Text Extractor",
      index: "Index Creator",
      typesetter: "Typesetter",
      prompt: "Prompt Extractor",
      image: "Image Generator",
      cover: "Cover Generator",
      graph: "Graph Generator",
      bio: "Diagram Generator",
      map: "Map Generator",
      grep: "GREP Builder",
      solutions: "Solutions Importer",
      scriptBuffet: "Script Buffet",
      barcode: "Barcode Generator",
      manual: "Design Manual",
      brand: "Brand Manual",
    },
    ready: "Ready to start",
    upload: "Drag image/PDF, paste, or click here to select file",
    another: "Another one",
    extractedText: "Extracted text",
    source: "Source",
    copyText: "Copy text",
    copied: "Copied",
    correctionPlaceholder: "Describe how the extracted text should be corrected…",
    correct: "Correct text",
    indexUpload: "Drag PDF, or click here to select file",
    wordList: "One index word or phrase per line",
    createIndex: "Create index",
    indexOutput: "Index output",
    indexLegend: "Term [Tab] Best match [Tab] All other matches",
    grepFind: "Find what",
    grepReplace: "Change to",
    generateGrep: "Generate GREP code",
    tryAgain: "Try again",
    pdfPage: "PDF page",
    printedPage: "Printed page",
    pageMapping: "Page-number anchor",
    localExtraction: "The PDF text stays in this browser",
    promptUpload: "Drag a manuscript PDF (up to 20 pages), or select",
    extractedPrompts: "Extracted prompts",
    noIllustrations: "No meaningful illustrations found.",
    comingSoon: "It’s nice to have something to look forward to.",
    processing: ["pouring a coffee", "sharpening pencils", "looking out of the window", "reading the small print", "straightening the paper", "finding the first line", "squinting at punctuation", "counting paragraphs", "checking the margins", "recognising letters", "putting words back in order"],
    indexProcessing: ["communicating", "calculating", "slicing bread", "spreading butter", "packing lunch", "looking up the way to the library", "waiting for the tram", "looking for a place to sit", "2+2=???", "hm…", "looking for a bench in the park", "consuming sandwich", "staring into space", "looking at trees"],
    promptProcessing: ["polishing the magnifier", "playing with the pen", "turning a page", "looking out of the window", "turning on the lamp", "hunching over the computer", "thinking about stuff", "procrastinating", "checking the horoscope", "taking a deep sigh", "thinking about things", "pouring a coffee", "doing some push-ups"],
    figureProcessing: ["unfolding a very large map", "looking for the tiny countries", "asking history what year it is", "checking whether the borders moved again", "putting the islands back", "consulting a suspiciously thick atlas", "straightening the coastlines", "negotiating with the label positions", "moving the legend out of the sea", "counting countries twice", "giving the SVG a final polish", "folding the map correctly on the first try"],
    diagramProcessing: ["checking the specimen labels", "peering through the microscope", "arranging the organelles", "untangling the leader lines", "counting the vacuoles", "centering the specimen", "sharpening the diagram pencils", "comparing the reference images", "checking what belongs where", "simplifying the anatomy", "making room for the labels", "giving the SVG a final polish"],
    graphProcessing: ["checking every supplied number", "reading the source line twice", "choosing sensible axes", "measuring the longest label", "counting the data points", "lining up the tick marks", "looking for a missing unit", "balancing the chart margins", "drawing the bars with a ruler", "joining the points", "checking the legend", "giving the SVG a final polish"],
    about: "About Taktik Robot",
    aboutBody:
      "A focused workspace for preparing textbook content, layouts and visual materials.",
    close: "Close information",
    home: "Taktik Robot home", changeLanguage: "Change language", toggleTheme: "Toggle color theme", openInformation: "Open information", tools: "Tools",
    pdfImageOnly: "Please use a PDF, PNG or JPG file.", pdfOnly: "Please use a PDF file.", fileTooLarge20: "The file is larger than the 20 MB limit.", fileTooLarge30: "The file is larger than the 30 MB limit.",
  },
  cs: {
    prompt: "Jdeme na to!",
    text: "Text",
    image: "Obraz",
    design: "Design",
    apps: {
      extraction: "Extraktor textu",
      index: "Tvůrce rejstříku",
      typesetter: "Sazeč",
      prompt: "Extraktor promptů",
      image: "Generátor obrázků",
      cover: "Generátor obálek",
      graph: "Generátor grafů",
      bio: "Generátor diagramů",
      map: "Generátor map",
      grep: "Tvůrce GREP výrazů",
      solutions: "Importér řešení",
      scriptBuffet: "Script Buffet",
      barcode: "Generátor čárových kódů",
      manual: "Grafický manuál",
      brand: "Brand manuál",
    },
    ready: "Připraveno",
    upload: "Přetáhněte obrázek/PDF, vložte, nebo klikněte pro výběr",
    another: "Další",
    extractedText: "Extrahovaný text",
    source: "Zdroj",
    copyText: "Kopírovat text",
    copied: "Zkopírováno",
    correctionPlaceholder: "Popište, jak má být extrahovaný text opraven…",
    correct: "Opravit text",
    indexUpload: "Přetáhněte PDF nebo klikněte pro výběr",
    wordList: "Jedno slovo nebo slovní spojení na řádek",
    createIndex: "Vytvořit rejstřík",
    indexOutput: "Výstup rejstříku",
    indexLegend: "Heslo [Tab] Nejlepší shoda [Tab] Všechny ostatní shody",
    grepFind: "Najít",
    grepReplace: "Změnit na",
    generateGrep: "Vygenerovat GREP kód",
    tryAgain: "Zkusit znovu",
    pdfPage: "Strana PDF",
    printedPage: "Tištěná strana",
    pageMapping: "Kotva číslování stran",
    localExtraction: "Text PDF zůstává v tomto prohlížeči",
    promptUpload: "Přetáhněte rukopis v PDF (max. 20 stran), nebo vyberte",
    extractedPrompts: "Extrahované prompty",
    noIllustrations: "Nebyly nalezeny žádné smysluplné ilustrace.",
    comingSoon: "Je to fajn mít se na co těšit.",
    processing: ["nalévání kávy", "ořezávání tužek", "koukání z okna", "čtení drobného písma", "rovnání papíru", "hledání prvního řádku", "mhouření očí nad interpunkcí", "počítání odstavců", "kontrola okrajů", "rozpoznávání písmen", "skládání slov do správného pořadí"],
    indexProcessing: ["komunikace", "kalkulace", "krájení chleba", "mazání chleba máslem", "balení svačiny", "vyhledávání cesty do knihovny", "čekání na tramvaj", "hledání místa k sezení", "2+2=???", "hm…", "hledání lavičky v parku", "konzumace svačiny", "koukání do blba", "koukání na stromy"],
    promptProcessing: ["leštění lupy", "hraní si s propiskou", "otáčení stránky", "koukání z okna", "rozsvěcení lampy", "hrbení se nad počítačem", "přemýšlení o všem možném", "prokrastinování", "kontrolování horoskopu", "hluboké povzdechnutí", "přemýšlení nad věcmi", "nalévání kávy", "dělání kliků"],
    figureProcessing: ["rozkládání opravdu velké mapy", "hledání těch nejmenších států", "dotazování historie, jaký je právě rok", "kontrola, zda se hranice zase neposunuly", "vracení ostrovů na jejich místa", "listování podezřele tlustým atlasem", "narovnávání pobřeží", "vyjednávání s pozicemi popisků", "stěhování legendy z moře", "dvojí počítání států", "závěrečné leštění SVG", "skládání mapy správně hned napoprvé"],
    diagramProcessing: ["kontrola popisků preparátu", "nahlížení do mikroskopu", "rovnání organel", "rozmotávání odkazových čar", "počítání vakuol", "centrování preparátu", "ořezávání tužek na schéma", "porovnávání referenčních obrázků", "kontrola, co kam patří", "zjednodušování anatomie", "uvolňování místa pro popisky", "závěrečné leštění SVG"],
    graphProcessing: ["kontrola každého zadaného čísla", "dvojí čtení zdroje", "volba rozumných os", "měření nejdelšího popisku", "počítání datových bodů", "rovnání značek na ose", "hledání chybějící jednotky", "vyvažování okrajů grafu", "rýsování sloupců", "spojování bodů", "kontrola legendy", "závěrečné leštění SVG"],
    about: "O aplikaci Taktik Robot",
    aboutBody:
      "Soustředěné pracovní prostředí pro přípravu učebnic, sazby a obrazových materiálů.",
    close: "Zavřít informace",
    home: "Domovská stránka Taktik Robot", changeLanguage: "Změnit jazyk", toggleTheme: "Přepnout barevný motiv", openInformation: "Otevřít informace", tools: "Nástroje",
    pdfImageOnly: "Použijte soubor PDF, PNG nebo JPG.", pdfOnly: "Použijte soubor PDF.", fileTooLarge20: "Soubor překračuje limit 20 MB.", fileTooLarge30: "Soubor překračuje limit 30 MB.",
  },
} as const;

export const coverUi = {
  en: {
    code: "IMAGE / COVER CONCEPTS", heading: "Cover Generator", active: "active sketches", selected: "direction selected", download: "DOWNLOAD ZIP ↓", exportArtboard: "EXPORT ARTBOARD ↓", artboardError: "No generated covers are visible in the viewport.", sketch: "SKETCH", choose: "↑ UPVOTED", upvote: "↑ UPVOTE", reject: "Delete cover", empty: "Add at least two existing covers, write a brief, and generate the first directions.", generating: "GENERATING", assets: "2K COVER MASTER & SEPARATE ASSETS", assetsNote: "AI-recreated from the selected composition with FLUX.2 Pro", artDirection: "ART DIRECTION", references: "REFERENCE COVERS", minimum: "2–3 covers", addCover: "ADD\nCOVER", remove: "Remove", brief: "WHAT SHOULD BE GENERATED?", placeholder: "Example: A lower-secondary science textbook cover about ecosystems. An intelligent, tactile illustration of a wetland food web; leave a calm clear area in the upper third for typography. Preserve the palette and visual rhythm of the reference covers.", generateTwo: "GENERATE 2", generateFour: "GENERATE 4", generateSelectedTwo: "GENERATE 2 FROM UPVOTE", generateSelectedFour: "GENERATE 4 FROM UPVOTE", generatingCount: "GENERATING", note: "If you like one of the generated covers and want to move in that direction, you can ‘Upvote it’ so that it’s used as an additional reference in the next batch. You can also delete the ones you don’t like.", manifest: "UPSCALE & SEPARATE ASSETS", manifestNote: "Select a concept above, then Robot automatically detects its essential objects, recreates a 2K cover master, and produces isolated 2K stems. This is AI recreation, not pixel-perfect layer extraction.", addObject: "+ ADD SEPARATE ASSET", newObject: "Describe another asset", generateAssets: "CREATE 2K MASTER & AUTOMATIC STEMS", generatingAssets: "CREATING 2K MASTER & STEMS…", asset: "Asset", close: "Close", zoom: "Zoom sketch", stock: "SHUTTERSTOCK RESEARCH", stockHelp: "Add one search phrase or direct Shutterstock URL per row. Empty rows fall back to the main brief.", stockInput: "Search phrase or direct Shutterstock URL", addStockInput: "+ ADD RESEARCH IMAGE", stockWarning: "Shutterstock previews are watermarked and unlicensed. License every used asset before publication; source links are included in the ZIP report.", limit: "Keep no more than 16 active sketches. Delete a few before generating more.", sketchError: "OpenRouter returned no cover sketches.", generationError: "Cover generation failed.", assetError: "OpenRouter returned no production assets.", productionError: "Production asset generation failed.", detectionError: "Automatic object detection failed.", masterError: "The 2K cover master failed.", referenceError: "A reference cover could not be prepared.", reportTitle: "Cover generation report", medium: "STYLE", mediumMatch: "Match references", mediumPhoto: "Photorealistic composite", mediumIllustration: "Illustration", medium3d: "3D render", sketchQuality: "GENERATION QUALITY", qualityFast: "Low quality, faster · flux.2-klein-4b · 512 px", qualityFidelity: "High quality, slower · flux.2-pro · 1K", fidelityNote: "High quality costs more, but follows photographic references and complex composites more reliably. The 2K master and stems use flux.2-pro.", artOnly: "IGNORE TEXT IN REFERENCE IMAGES", artOnlyHelp: "Ignore book titles, grade labels, publisher logos and other text in the reference images. This may help generate cleaner cover art.",
  },
  cs: {
    code: "OBRAZ / NÁVRHY OBÁLEK", heading: "Generátor obálek", active: "aktivních návrhů", selected: "směr vybrán", download: "STÁHNOUT ZIP ↓", exportArtboard: "EXPORTOVAT PLOCHU ↓", artboardError: "V aktuálním výřezu nejsou viditelné žádné vygenerované obálky.", sketch: "NÁVRH", choose: "↑ HLAS PŘIDÁN", upvote: "↑ HLASOVAT PRO", reject: "Smazat obálku", empty: "Přidejte alespoň dvě existující obálky, napište zadání a vygenerujte první směry.", generating: "GENERUJI", assets: "2K HLAVNÍ OBÁLKA A SAMOSTATNÉ PODKLADY", assetsNote: "Nově vytvořeno z vybrané kompozice modelem FLUX.2 Pro", artDirection: "VÝTVARNÝ SMĚR", references: "REFERENČNÍ OBÁLKY", minimum: "2–3 obálky", addCover: "PŘIDAT\nOBÁLKU", remove: "Odstranit", brief: "CO SE MÁ VYGENEROVAT?", placeholder: "Příklad: Obálka učebnice přírodopisu pro 2. stupeň o ekosystémech. Inteligentní, haptická ilustrace potravní sítě mokřadu; v horní třetině ponechte klidné místo pro typografii. Zachovejte barevnost a vizuální rytmus referenčních obálek.", generateTwo: "VYGENEROVAT 2", generateFour: "VYGENEROVAT 4", generateSelectedTwo: "VYGENEROVAT 2 PODLE HLASU", generateSelectedFour: "VYGENEROVAT 4 PODLE HLASU", generatingCount: "GENERUJI", note: "Pokud se vám některá vygenerovaná obálka líbí a chcete pokračovat tímto směrem, můžete pro ni hlasovat; v další sadě se použije jako dodatečná reference. Obálky, které se vám nelíbí, můžete také smazat.", manifest: "ZVĚTŠIT A VYTVOŘIT SAMOSTATNÉ PODKLADY", manifestNote: "Vyberte koncept nahoře. Robot automaticky rozpozná hlavní objekty, vytvoří hlavní obálku ve 2K a izolované 2K podklady. Jde o novou tvorbu AI, nikoli přesné vytažení vrstev z pixelů.", addObject: "+ PŘIDAT SAMOSTATNÝ PODKLAD", newObject: "Popište další podklad", generateAssets: "VYTVOŘIT 2K OBÁLKU A AUTOMATICKÉ PODKLADY", generatingAssets: "VYTVÁŘÍM 2K OBÁLKU A PODKLADY…", asset: "Podklad", close: "Zavřít", zoom: "Zvětšit návrh", stock: "REŠERŠE SHUTTERSTOCK", stockHelp: "Přidejte do každého řádku jeden vyhledávací dotaz nebo přímý odkaz Shutterstock. Prázdné řádky použijí hlavní zadání.", stockInput: "Vyhledávací dotaz nebo přímý odkaz Shutterstock", addStockInput: "+ PŘIDAT OBRÁZEK PRO REŠERŠI", stockWarning: "Náhledy Shutterstock jsou opatřené vodoznakem a bez licence. Každý použitý podklad před publikací licencujte; odkazy budou v reportu uvnitř ZIP.", limit: "Ponechte nejvýše 16 aktivních návrhů. Před dalším generováním některé smažte.", sketchError: "OpenRouter nevrátil žádné návrhy obálky.", generationError: "Generování obálky selhalo.", assetError: "OpenRouter nevrátil žádné produkční podklady.", productionError: "Generování produkčních podkladů selhalo.", detectionError: "Automatické rozpoznání objektů selhalo.", masterError: "Vytvoření hlavní obálky ve 2K selhalo.", referenceError: "Referenční obálku se nepodařilo připravit.", reportTitle: "Report generování obálky", medium: "STYL", mediumMatch: "Podle referencí", mediumPhoto: "Fotorealistická koláž", mediumIllustration: "Ilustrace", medium3d: "3D render", sketchQuality: "KVALITA GENEROVÁNÍ", qualityFast: "Nižší kvalita, rychlejší · flux.2-klein-4b · 512 px", qualityFidelity: "Vyšší kvalita, pomalejší · flux.2-pro · 1K", fidelityNote: "Vyšší kvalita stojí více, ale spolehlivěji následuje fotografické reference a složité koláže. Hlavní obálka a podklady ve 2K používají flux.2-pro.", artOnly: "IGNOROVAT TEXT V REFERENČNÍCH OBRÁZCÍCH", artOnlyHelp: "Ignorovat názvy knih, označení ročníků, loga nakladatele a další text v referenčních obrázcích. To může pomoci vytvořit čistší obrazovou část obálky.",
  },
} as const;

export const localizedCoverUi = {
  en: { ...coverUi.en, exportArtboard: "EXPORT ARTBOARD PDF ↓" },
  cs: { ...coverUi.cs, exportArtboard: "EXPORTOVAT PLOCHU DO PDF ↓" },
} as const;

export const robotStatusPhrases = {
  en: ["CONNECTED TO THE MATRIX", "ČAPEK IS ONLINE", "ROSSUM'S SERVER IS RUNNING", "THE ROBOTS REPORT READY", "DOMIN'S TERMINAL RESPONDS"],
  cs: ["PŘIPOJENO K MATRIXU", "ČAPEK JE ONLINE", "ROSSUMŮV SERVER BĚŽÍ", "ROBOTI HLÁSÍ PŘIPRAVENO", "DOMINŮV TERMINÁL ODPOVÍDÁ"],
} as const;

export const figureUi = {
  en: {
    heading: "Figure Generator", subtitle: "Create source-backed SVG charts, diagrams, and factual maps. Specifications are validated and coordinates are rendered by code.", badge: "VERIFIED PIPELINE",
    label: "FACTS, VALUES AND SOURCES", placeholder: "Example: Make a line chart titled …\n2022: 18.4\n2023: 21.1\n2024: 23.7\nUnit: percent\nSource: Statistical office, https://…",
    generate: "Generate SVG (about 30 seconds)", generating: "Generating SVG", preview: "SVG PREVIEW", checks: "AUTOMATED CHECKS", downloadSvg: "Download SVG", downloadReport: "Download verification report (.md)", empty: "Nothing scarier than an empty page.", warning: "Charts validate supplied data. Diagrams and schematic maps require editorial review; maps research and cite web sources for every region.", example: "Insert example", chart: "Data graph", diagram: "Biological diagram", map: "Factual map", references: "REFERENCE IMAGES (OPTIONAL, MAX. 3)", addReference: "Add reference image", remove: "Remove", palette: "COLOR PALETTE (OPTIONAL)", addPalette: "Add Adobe swatches (.ase)", clearPalette: "Remove palette", timeline: "HISTORICAL BOUNDARY TIMELINE", timelineLoading: "Loading dated boundaries…",
    negativeBce: "NEGATIVE = BCE", previousYear: "Previous year", nextYear: "Next year", mapYear: "Map year; use negative numbers for BCE", historicalTimeline: "Historical timeline", bce: "BCE", ce: "CE", layers: "LAYERS", mapLayers: { boundaries: "borders", labels: "country names", water: "seas and oceans", rivers: "rivers", climate: "climate zones", terrain: "terrain regions", mountains: "mountain ranges", cities: "cities and capitals", disputed: "disputed boundaries" }, climateNote: "Köppen–Geiger zones represent 1980–2016 climate normals, independently of the selected political year.", climateLabels: ["Tropical", "Arid", "Temperate", "Cold", "Polar"], presentLayersNote: "These Natural Earth layers describe present-day geography and boundaries, independently of the selected historical year.", fillCountries: "FILL COUNTRIES", on: "ON", zoomIn: "Zoom +", zoomOut: "Zoom −", resetView: "Reset view", mapInstructions: "Drag to pan. Activate Fill countries before clicking territories. Changes are preserved in the downloaded SVG.", adobePalette: "ADOBE PALETTE", replacePalette: "Replace .ase", applyPalette: "Apply", shufflePalette: "Shuffle", importPalette: "Import .ase palette", editMap: "EDIT MAP WITH A PROMPT", mapPrompt: "For example: Fill NATO members blue and label the Baltic Sea.", warnings: "WARNINGS", paletteFileError: "Choose an Adobe Swatch Exchange (.ase) file up to 2 MB.", paletteReadError: "Could not read the ASE palette.",
  },
  cs: {
    heading: "Generátor ilustrací", subtitle: "Vytváří zdrojované SVG grafy, schémata a faktické mapy. Specifikace ověří a souřadnice vykreslí kód.", badge: "OVĚŘOVANÝ POSTUP",
    label: "FAKTA, HODNOTY A ZDROJE", placeholder: "Příklad: Vytvoř spojnicový graf s názvem …\n2022: 18,4\n2023: 21,1\n2024: 23,7\nJednotka: procenta\nZdroj: Statistický úřad, https://…",
    generate: "Vytvořit SVG (asi 30 sekund)", generating: "Vytváření SVG", preview: "NÁHLED SVG", checks: "AUTOMATICKÉ KONTROLY", downloadSvg: "Stáhnout SVG", downloadReport: "Stáhnout protokol kontroly (.md)", empty: "Není nic děsivějšího než prázdná stránka.", warning: "Grafy ověřují dodaná data. Schémata i schematické mapy vyžadují redakční kontrolu; mapy vyhledávají a citují webové zdroje pro každou oblast.", example: "Vložit příklad", chart: "Datový graf", diagram: "Biologické schéma", map: "Faktická mapa", references: "REFERENČNÍ OBRÁZKY (VOLITELNÉ, MAX. 3)", addReference: "Přidat referenční obrázek", remove: "Odstranit", palette: "BAREVNÁ PALETA (VOLITELNÉ)", addPalette: "Přidat vzorník Adobe (.ase)", clearPalette: "Odstranit paletu", timeline: "ČASOVÁ OSA HISTORICKÝCH HRANIC", timelineLoading: "Načítám dobové hranice…",
    negativeBce: "ZÁPORNÉ ČÍSLO = PŘ. N. L.", previousYear: "Předchozí rok", nextYear: "Následující rok", mapYear: "Rok mapy; pro období př. n. l. použijte záporné číslo", historicalTimeline: "Historická časová osa", bce: "PŘ. N. L.", ce: "N. L.", layers: "VRSTVY", mapLayers: { boundaries: "hranice", labels: "názvy států", water: "moře a oceány", rivers: "řeky", climate: "klimatická pásma", terrain: "oblasti reliéfu", mountains: "pohoří", cities: "města a hlavní města", disputed: "sporné hranice" }, climateNote: "Pásma Köppenovy–Geigerovy klasifikace představují klimatické normály z let 1980–2016 bez ohledu na zvolený politický rok.", climateLabels: ["Tropické", "Suché", "Mírné", "Chladné", "Polární"], presentLayersNote: "Tyto vrstvy Natural Earth popisují současnou geografii a hranice bez ohledu na zvolený historický rok.", fillCountries: "VYBARVIT STÁTY", on: "ZAPNUTO", zoomIn: "Přiblížit +", zoomOut: "Oddálit −", resetView: "Obnovit pohled", mapInstructions: "Tažením mapu posunete. Před kliknutím na území zapněte Vybarvit státy. Změny se zachovají ve staženém SVG.", adobePalette: "PALETA ADOBE", replacePalette: "Nahradit .ase", applyPalette: "Použít", shufflePalette: "Promíchat", importPalette: "Importovat paletu .ase", editMap: "UPRAVIT MAPU PROMPTEM", mapPrompt: "Například: Vybarvi členy NATO modře a popiš Baltské moře.", warnings: "UPOZORNĚNÍ", paletteFileError: "Vyberte soubor Adobe Swatch Exchange (.ase) o velikosti nejvýše 2 MB.", paletteReadError: "Paletu ASE se nepodařilo načíst.",
  },
} as const;
export const solutionsImporterUi = {
  en: {
    heading: "Solutions Importer",
    subtitle: "Turn a clean PDF, the editor's annotated manuscript, and matching IDML into reviewable InDesign operations for text, tables, marks, and native colour fills.",
    local: "PROCESSED LOCALLY",
    clean: "CLEAN PDF",
    manuscript: "ANNOTATED MANUSCRIPT PDF",
    idml: "MATCHING CLEAN IDML",
    printersMarks: "One or both PDFs include printer's marks",
    printersMarksHelp: "Normalize both PDFs to their embedded TrimBox so bleed and print marks do not shift the InDesign coordinates.",
    printersMarksLog: "Printer-mark normalization enabled: using each PDF TrimBox as the InDesign page.",
    solutionTypography: "SOLUTION TYPOGRAPHY",
    solutionFont: "Font",
    solutionSize: "Size",
    choose: "Drop file here or choose",
    analyse: "Analyse chapter",
    analyseAgain: "Analyse again",
    analysing: "Analysing chapter…",
    processLog: "LOCAL PROCESS LOG",
    privacy: "Python, pdfplumber, and the IDML parser run inside this browser. The PDFs, IDML, annotations, and extracted text are never uploaded.",
    starting: "Starting local chapter analysis. No files will be uploaded.",
    failed: "Could not analyse the chapter files.",
    ready: "Analysis complete. Review uncertain operations before downloading the JSON.",
    error: "ERROR",
    pdfError: "Please choose a PDF file.",
    idmlError: "Please choose an IDML file.",
    reviewKicker: "IMPORT PLAN",
    reviewHeading: "Review detected solutions",
    downloadJson: "Download reviewed JSON",
    pages: "PAGES",
    textOperations: "TEXT",
    visualMarks: "MARKS",
    idmlTables: "TABLES",
    needsReview: "REVIEW",
    excluded: "EXCLUDED",
    reviewFilter: "Filter detected operations",
    filters: { all: "All", ready: "Ready", review: "Needs review" },
    pdfPage: "PDF page",
    bookPage: "book page",
    operations: "operations",
    reviewShort: "review",
    kinds: { text: "Text", cross: "Cross", circle: "Circle", color_mark: "Colour", note: "Note" },
    colour: "Colour family",
    positionedMark: "Positioned manuscript mark",
    reviewNote: "Likely source-text edits and notes are initially unticked. Re-enable any that are genuine answers; colour marks remain included but are flagged for visual review.",
    download: "DOWNLOAD FOR INDESIGN",
    simpleImporter: "Simple InDesign script",
    advancedImporter: "Advanced InDesign script",
    scriptChoice: "Start with Advanced for tables and aligned answer boxes. If it fails or places something incorrectly, run Simple: it only places the reviewed text at the PDF coordinates and is more failsafe.",
    need: "YOU WILL NEED",
    needs: ["Clean chapter PDF", "Annotated solutions manuscript PDF", "Clean IDML from the matching chapter", "A copy of the matching InDesign chapter"],
    warningTitle: "Run either importer on a copy.",
    warning: "Linked Illustrator and Photoshop artwork is reported for manual handling and is never modified.",
    steps: [
      ["Prepare three matching files", "Export the clean chapter PDF and IDML from the same InDesign file. Add the editor's annotated manuscript PDF with exactly the same pages and page order. If either PDF includes bleed or printer's marks, enable the checkbox above."],
      ["Analyse and review", "Choose the three files above and select the solution font and size. Robot separates added text from the clean PDF, reads PDF annotations, and inspects the IDML for page names, tables, styles, swatches, and linked artwork. Use the filters and checkboxes to remove false detections."],
      ["Download the operation JSON", "Download the reviewed JSON and keep it beside the matching chapter. It contains positioned operations and IDML metadata, not the source documents."],
      ["Install one or both scripts", "Download import_solutions_simple.jsx, import_solutions_advanced.jsx, or both. In InDesign choose Window → Utilities → Scripts, reveal the User scripts folder, and place the JSX files in Scripts Panel. Installation is needed only once."],
      ["Import and check", "Open a copy of the matching InDesign chapter and choose the reviewed JSON. Advanced maps answers into table cells and aligns answer frames. Simple places each answer directly at its PDF coordinates. If Advanced fails, undo it and try Simple."],
    ],
    checks: ["Check operations marked for review first.", "Check that each answer snapped to the intended box; unusually open layouts may not provide a detectable container.", "Check every duplicated table and resolved colour against the task's existing palette.", "Advanced replaces existing SOLUTIONS-layer page items after a successful import; always work on a versioned copy.", "One Undo removes a completed import."],
    trouble: "If it does not work",
    troubles: [
      ["Page count or names do not match", "Re-export the clean PDF and IDML from the same chapter, then make sure the manuscript contains those exact pages in the same order. Enable printer-mark normalization when a PDF page includes bleed or marks."],
      ["A grid was not filled", "Compact numeric grids are filled automatically. Large writing grids containing solution words or letters are intentionally left as ordinary text frames and marked with a nonprinting magenta review rectangle."],
      ["A colour is uncertain", "Annotation colour selects a hue family; the script chooses a nearby document swatch used in that task. Review the result when several similar swatches are available."],
      ["Artwork is not changed", "Linked AI, PSD, and raster artwork is intentionally left alone. Edit those few files manually and relink them in InDesign."],
    ],
  },
  cs: {
    heading: "Importér řešení",
    subtitle: "Převede čisté PDF, redakční rukopis s anotacemi a odpovídající IDML na kontrolovatelný plán pro texty, tabulky, značky a barevné výplně v InDesignu.",
    local: "ZPRACOVÁNO MÍSTNĚ",
    clean: "ČISTÉ PDF",
    manuscript: "ANOTOVANÝ RUKOPIS PDF",
    idml: "ODPOVÍDAJÍCÍ ČISTÉ IDML",
    printersMarks: "Jedno nebo obě PDF obsahují tiskové značky",
    printersMarksHelp: "Normalizuje obě PDF podle vloženého TrimBoxu, aby spadávka a tiskové značky neposunuly souřadnice v InDesignu.",
    printersMarksLog: "Normalizace tiskových značek je zapnutá: jako strana InDesignu se použije TrimBox každého PDF.",
    solutionTypography: "TYPOGRAFIE ŘEŠENÍ",
    solutionFont: "Písmo",
    solutionSize: "Velikost",
    choose: "Přetáhněte soubor nebo jej vyberte",
    analyse: "Analyzovat kapitolu",
    analyseAgain: "Analyzovat znovu",
    analysing: "Analyzuji kapitolu…",
    processLog: "MÍSTNÍ PROTOKOL ZPRACOVÁNÍ",
    privacy: "Python, pdfplumber a parser IDML běží v tomto prohlížeči. PDF, IDML, anotace ani extrahovaný text se nikam nenahrávají.",
    starting: "Spouštím místní analýzu kapitoly. Žádné soubory se nebudou nahrávat.",
    failed: "Soubory kapitoly se nepodařilo analyzovat.",
    ready: "Analýza je hotová. Před stažením JSON zkontrolujte nejisté operace.",
    error: "CHYBA",
    pdfError: "Vyberte soubor PDF.",
    idmlError: "Vyberte soubor IDML.",
    reviewKicker: "PLÁN IMPORTU",
    reviewHeading: "Kontrola nalezených řešení",
    downloadJson: "Stáhnout zkontrolovaný JSON",
    pages: "STRANY",
    textOperations: "TEXTY",
    visualMarks: "ZNAČKY",
    idmlTables: "TABULKY",
    needsReview: "KONTROLA",
    excluded: "VYŘAZENO",
    reviewFilter: "Filtrovat nalezené operace",
    filters: { all: "Vše", ready: "Připravené", review: "Ke kontrole" },
    pdfPage: "Strana PDF",
    bookPage: "strana knihy",
    operations: "operací",
    reviewShort: "ke kontrole",
    kinds: { text: "Text", cross: "Křížek", circle: "Kroužek", color_mark: "Barva", note: "Poznámka" },
    colour: "Barevná rodina",
    positionedMark: "Umístěná značka z rukopisu",
    reviewNote: "Pravděpodobné redakční změny textu a poznámky jsou zpočátku odškrtnuté. Skutečná řešení znovu povolte; barevné značky zůstávají zahrnuté, ale vyžadují vizuální kontrolu.",
    download: "STÁHNOUT PRO INDESIGN",
    simpleImporter: "Jednoduchý skript pro InDesign",
    advancedImporter: "Pokročilý skript pro InDesign",
    scriptChoice: "Začněte pokročilým skriptem pro tabulky a zarovnaná pole odpovědí. Pokud selže nebo něco umístí špatně, spusťte jednoduchý: pouze vloží zkontrolovaný text na souřadnice z PDF a je spolehlivější.",
    need: "BUDETE POTŘEBOVAT",
    needs: ["Čisté PDF kapitoly", "Anotovaný rukopis řešení v PDF", "Čisté IDML odpovídající kapitoly", "Kopii odpovídající kapitoly InDesignu"],
    warningTitle: "Kterýkoli importér spusťte na kopii.",
    warning: "Propojené soubory Illustratoru a Photoshopu se pouze uvedou ke kontrole a nikdy se automaticky nemění.",
    steps: [
      ["Připravte tři odpovídající soubory", "Čisté PDF kapitoly a IDML exportujte ze stejného souboru InDesignu. Přidejte redakční rukopis s přesně stejnými stranami a pořadím. Pokud některé PDF obsahuje spadávku nebo tiskové značky, zapněte volbu nahoře."],
      ["Analyzujte a zkontrolujte", "Vyberte tři soubory nahoře a zvolte písmo a velikost řešení. Robot oddělí přidaný text od čistého PDF, přečte anotace PDF a zkontroluje v IDML názvy stran, tabulky, styly, vzorník a propojenou grafiku. Filtry a zaškrtávátky odstraňte chybné nálezy."],
      ["Stáhněte JSON s operacemi", "Zkontrolovaný JSON uložte k odpovídající kapitole. Obsahuje umístěné operace a metadata IDML, nikoli zdrojové dokumenty."],
      ["Nainstalujte jeden nebo oba skripty", "Stáhněte import_solutions_simple.jsx, import_solutions_advanced.jsx nebo oba. V InDesignu zvolte Okna → Pomůcky → Skripty, otevřete uživatelskou složku skriptů a vložte soubory JSX do Scripts Panel. Instalaci stačí provést jednou."],
      ["Importujte a zkontrolujte", "Otevřete kopii odpovídající kapitoly a vyberte zkontrolovaný JSON. Pokročilý skript vkládá odpovědi do buněk tabulek a zarovnává textová pole. Jednoduchý vloží každou odpověď přímo na souřadnice z PDF. Pokud pokročilý selže, vraťte krok zpět a zkuste jednoduchý."],
    ],
    checks: ["Nejdříve projděte operace označené ke kontrole.", "Ověřte, že každé řešení zapadlo do správného pole; ve velmi otevřeném layoutu nemusí být kontejner rozpoznatelný.", "Zkontrolujte každou duplikovanou tabulku a zvolenou barvu podle palety úlohy.", "Pokročilý skript po úspěšném importu nahradí stávající objekty ve vrstvě SOLUTIONS; vždy pracujte s verzovanou kopií.", "Jeden krok Zpět odstraní celý dokončený import."],
    trouble: "Když něco nefunguje",
    troubles: [
      ["Nesouhlasí počet nebo názvy stran", "Čisté PDF a IDML znovu exportujte ze stejné kapitoly a ověřte, že rukopis obsahuje přesně stejné strany ve stejném pořadí. Pokud PDF obsahuje spadávku nebo značky, zapněte normalizaci tiskových značek."],
      ["Mřížka se nevyplnila", "Kompaktní číselné mřížky se vyplňují automaticky. Velké psací mřížky, jejichž řešení obsahuje slova nebo písmena, záměrně zůstanou jako běžné textové rámečky a označí se netisknutelným purpurovým kontrolním obdélníkem."],
      ["Barva není jistá", "Barva anotace určuje barevnou rodinu; skript vybere blízký vzorek dokumentu použitý v dané úloze. Když je podobných vzorků více, výsledek zkontrolujte."],
      ["Grafika se nezměnila", "Propojené AI, PSD a rastrové soubory se záměrně nemění. Těchto několik souborů upravte ručně a v InDesignu je znovu propojte."],
    ],
  },
} as const;
export const barcodeUi = {
  en: {
    heading: "Barcode Generator", subtitle: "Enter an ISBN with or without hyphens. Download a press-ready vector EAN-13 PDF.", local: "CREATED LOCALLY",
    label: "ISBN-10 OR ISBN-13", placeholder: "978-80-7563-123-4", generate: "Download vector PDF", ready: "READY FOR PRODUCTION", empty: "Enter an ISBN to preview the barcode.",
    valid: "CHECKSUM VALID", converted: "ISBN-10 CONVERTED", format: "EAN-13", size: "37.29 × 25.93 MM", colour: "CMYK 0 / 0 / 0 / 100", type: "VERDANA · OUTLINED", privacy: "Everything is generated in this browser. No ISBN is uploaded.",
  },
  cs: {
    heading: "Generátor čárových kódů", subtitle: "Zadejte ISBN s pomlčkami nebo bez nich. Stáhněte tiskové vektorové PDF EAN-13.", local: "VYTVOŘENO MÍSTNĚ",
    label: "ISBN-10 NEBO ISBN-13", placeholder: "978-80-7563-123-4", generate: "Stáhnout vektorové PDF", ready: "PŘIPRAVENO PRO TISK", empty: "Zadejte ISBN pro náhled čárového kódu.",
    valid: "KONTROLNÍ ČÍSLICE PLATÍ", converted: "ISBN-10 PŘEVEDENO", format: "EAN-13", size: "37,29 × 25,93 MM", colour: "CMYK 0 / 0 / 0 / 100", type: "VERDANA · V KŘIVKÁCH", privacy: "Vše se generuje v tomto prohlížeči. ISBN se nikam neodesílá.",
  },
} as const;
export const brandGuidelinesUrl = "https://drive.google.com/open?id=1RGk5Wju28DMBMia1gd9ONdjYH0mQmiTC&usp=drive_fs";
