export const copy = {
  en: {
    prompt: "Let’s go!",
    text: "Text",
    image: "Image",
    design: "Design",
    apps: {
      extraction: "Text Extractor",
      index: "Index Creator",
      typesetter: "Typesetter",
      prompt: "Prompt Extractor",
      image: "Image Generator",
      cover: "Cover Generator",
      conceptIllustrator: "Concept Illustrator",
      layerSplitter: "Layer Splitter",
      graph: "Graph Generator",
      bio: "Diagram Generator",
      map: "Map Maker",
      grep: "GREP Builder",
      coverSplitter: "Cover Splitter",
      solutions: "Solutions Importer",
      scriptBuffet: "Script Buffet",
      barcode: "Barcode Generator",
      manual: "Design Manual",
      brand: "Brand Manual",
    },
    ready: "Ready to start",
    comingSoon: "It’s nice to have something to look forward to.",
    about: "About Taktik Robot",
    close: "Close information",
    home: "Taktik Robot home",
    changeLanguage: "Change language",
    toggleTheme: "Toggle color theme",
    openInformation: "Open information",
    tools: "Tools",
    bugFeedback: {
      eyebrow: "BUG REPORT",
      heading: "Bugs and Feedback",
      intro:
        "Tell us what happened. Robot will send this description and the safe diagnostics below to the feedback project.",
      dataTitle: "Information that will be sent",
      privacy:
        "Uploaded files, extracted text, prompts, generated images, and credentials are not included.",
      user: "Robot user",
      tool: "Current tool",
      status: "Status",
      input: "Input",
      inputPresent: "input present",
      none: "none",
      path: "Page",
      captured: "Captured",
      home: "Taktik Robot home",
      descriptionLabel: "What happened?",
      descriptionPlaceholder: "Describe the problem or feedback…",
      descriptionRequired: "Please describe what happened.",
      submit: "Send feedback",
      submitting: "Sending…",
      submitError: "Feedback could not be sent. Please try again.",
      cancel: "Cancel",
      close: "Close feedback",
      success: "Thanks — your feedback was sent to Asana.",
      taskCreated: "The task was created successfully.",
      openTask: "Open task in Asana",
      statuses: {
        idle: "idle",
        running: "running",
        completed: "completed",
        error: "error",
      },
    },
  },
  cs: {
    prompt: "Jdeme na to!",
    text: "Text",
    image: "Obraz",
    design: "Design",
    apps: {
      extraction: "Extraktor textu",
      index: "Tvůrce rejstříku",
      typesetter: "Sazeč",
      prompt: "Extraktor promptů",
      image: "Generátor obrázků",
      cover: "Generátor obálek",
      conceptIllustrator: "Koncept ilustrace",
      layerSplitter: "Rozdělovač vrstev",
      graph: "Generátor grafů",
      bio: "Generátor diagramů",
      map: "Tvůrce map",
      grep: "Tvůrce GREP výrazů",
      coverSplitter: "Dělení obálek",
      solutions: "Importér řešení",
      scriptBuffet: "Script Buffet",
      barcode: "Generátor čárových kódů",
      manual: "Grafický manuál",
      brand: "Brand manuál",
    },
    ready: "Připraveno",
    comingSoon: "Je to fajn mít se na co těšit.",
    about: "O aplikaci Taktik Robot",
    close: "Zavřít informace",
    home: "Domovská stránka Taktik Robot",
    changeLanguage: "Změnit jazyk",
    toggleTheme: "Přepnout barevný motiv",
    openInformation: "Otevřít informace",
    tools: "Nástroje",
    bugFeedback: {
      eyebrow: "HLÁŠENÍ CHYBY",
      heading: "Chyby a zpětná vazba",
      intro:
        "Popište, co se stalo. Robot odešle váš popis a níže uvedené bezpečné diagnostické údaje do projektu se zpětnou vazbou.",
      dataTitle: "Informace, které budou odeslány",
      privacy:
        "Nahrané soubory, extrahovaný text, prompty, vygenerované obrázky ani přihlašovací údaje nejsou součástí hlášení.",
      user: "Uživatel Robota",
      tool: "Aktuální nástroj",
      status: "Stav",
      input: "Vstup",
      inputPresent: "vstup je k dispozici",
      none: "žádný",
      path: "Stránka",
      captured: "Zachyceno",
      home: "Domovská stránka Taktik Robot",
      descriptionLabel: "Co se stalo?",
      descriptionPlaceholder: "Popište problém nebo zpětnou vazbu…",
      descriptionRequired: "Popište prosím, co se stalo.",
      submit: "Odeslat zpětnou vazbu",
      submitting: "Odesílání…",
      submitError:
        "Zpětnou vazbu se nepodařilo odeslat. Zkuste to prosím znovu.",
      cancel: "Zrušit",
      close: "Zavřít zpětnou vazbu",
      success: "Děkujeme — vaše zpětná vazba byla odeslána do Asany.",
      taskCreated: "Úkol byl úspěšně vytvořen.",
      openTask: "Otevřít úkol v Asaně",
      statuses: {
        idle: "nečinný",
        running: "probíhá",
        completed: "dokončeno",
        error: "chyba",
      },
    },
  },
} as const;

export const robotStatusPhrases = {
  en: [
    "CONNECTED TO THE MATRIX",
    "ČAPEK IS ONLINE",
    "ROSSUM'S SERVER IS RUNNING",
    "THE ROBOTS REPORT READY",
    "DOMIN'S TERMINAL RESPONDS",
  ],
  cs: [
    "PŘIPOJENO K MATRIXU",
    "ČAPEK JE ONLINE",
    "ROSSUMŮV SERVER BĚŽÍ",
    "ROBOTI HLÁSÍ PŘIPRAVENO",
    "DOMINŮV TERMINÁL ODPOVÍDÁ",
  ],
} as const;

export const brandGuidelinesUrl =
  "https://drive.google.com/open?id=1RGk5Wju28DMBMia1gd9ONdjYH0mQmiTC&usp=drive_fs";
