export const copy = {
  en: {
    prompt: "Let’s go!",
    text: "Text",
    image: "Image",
    design: "Design",
    apps: {
      extraction: "Text Extractor",
      index: "Index Creator",
      typesetter: "Typesetter",
      prompt: "Prompt Extractor",
      image: "Image Generator",
      cover: "Cover Generator",
      layerSplitter: "Layer Splitter",
      graph: "Graph Generator",
      bio: "Diagram Generator",
      map: "Map Generator",
      grep: "GREP Builder",
      coverSplitter: "Cover Splitter",
      solutions: "Solutions Importer",
      scriptBuffet: "Script Buffet",
      barcode: "Barcode Generator",
      manual: "Design Manual",
      brand: "Brand Manual",
    },
    ready: "Ready to start",
    comingSoon: "It’s nice to have something to look forward to.",
    about: "About Taktik Robot",
    close: "Close information",
    home: "Taktik Robot home",
    changeLanguage: "Change language",
    toggleTheme: "Toggle color theme",
    openInformation: "Open information",
    tools: "Tools",
  },
  cs: {
    prompt: "Jdeme na to!",
    text: "Text",
    image: "Obraz",
    design: "Design",
    apps: {
      extraction: "Extraktor textu",
      index: "Tvůrce rejstříku",
      typesetter: "Sazeč",
      prompt: "Extraktor promptů",
      image: "Generátor obrázků",
      cover: "Generátor obálek",
      layerSplitter: "Rozdělovač vrstev",
      graph: "Generátor grafů",
      bio: "Generátor diagramů",
      map: "Generátor map",
      grep: "Tvůrce GREP výrazů",
      coverSplitter: "Dělení obálek",
      solutions: "Importér řešení",
      scriptBuffet: "Script Buffet",
      barcode: "Generátor čárových kódů",
      manual: "Grafický manuál",
      brand: "Brand manuál",
    },
    ready: "Připraveno",
    comingSoon: "Je to fajn mít se na co těšit.",
    about: "O aplikaci Taktik Robot",
    close: "Zavřít informace",
    home: "Domovská stránka Taktik Robot",
    changeLanguage: "Změnit jazyk",
    toggleTheme: "Přepnout barevný motiv",
    openInformation: "Otevřít informace",
    tools: "Nástroje",
  },
} as const;

export const robotStatusPhrases = {
  en: [
    "CONNECTED TO THE MATRIX",
    "ČAPEK IS ONLINE",
    "ROSSUM'S SERVER IS RUNNING",
    "THE ROBOTS REPORT READY",
    "DOMIN'S TERMINAL RESPONDS",
  ],
  cs: [
    "PŘIPOJENO K MATRIXU",
    "ČAPEK JE ONLINE",
    "ROSSUMŮV SERVER BĚŽÍ",
    "ROBOTI HLÁSÍ PŘIPRAVENO",
    "DOMINŮV TERMINÁL ODPOVÍDÁ",
  ],
} as const;

export const brandGuidelinesUrl =
  "https://drive.google.com/open?id=1RGk5Wju28DMBMia1gd9ONdjYH0mQmiTC&usp=drive_fs";
