export const textExtractorCopy = {
  en: {
    heading: "Text Extractor",
    upload: "Drag image/PDF, paste, or click here to select file",
    another: "Another",
    extractedText: "Extracted text",
    source: "Source",
    emptySource: "Drop file here, paste, or click to select",
    copyText: "Copy text",
    copied: "Copied",
    correctionPlaceholder:
      "Describe how the extracted text should be corrected…",
    correct: "Correct text",
    processing: [
      "pouring a coffee",
      "sharpening pencils",
      "looking out of the window",
      "reading the small print",
      "straightening the paper",
      "finding the first line",
      "squinting at punctuation",
      "counting paragraphs",
      "checking the margins",
      "recognising letters",
      "putting words back in order",
    ],
    invalidFile: "Please use a PDF, PNG or JPG file.",
    fileTooLarge: "The file is larger than the 20 MB limit.",
    providerRateLimited:
      "The OCR provider is temporarily busy. Please retry shortly.",
  },
  cs: {
    heading: "Extraktor textu",
    upload: "Přetáhněte obrázek/PDF, vložte, nebo klikněte pro výběr",
    another: "Další",
    extractedText: "Extrahovaný text",
    source: "Zdroj",
    emptySource: "Přetáhněte soubor sem, vložte ho nebo klikněte pro výběr",
    copyText: "Kopírovat text",
    copied: "Zkopírováno",
    correctionPlaceholder: "Popište, jak má být extrahovaný text opraven…",
    correct: "Opravit text",
    processing: [
      "nalévání kávy",
      "ořezávání tužek",
      "koukání z okna",
      "čtení drobného písma",
      "rovnání papíru",
      "hledání prvního řádku",
      "mhouření očí nad interpunkcí",
      "počítání odstavců",
      "kontrola okrajů",
      "rozpoznávání písmen",
      "skládání slov do správného pořadí",
    ],
    invalidFile: "Použijte soubor PDF, PNG nebo JPG.",
    fileTooLarge: "Soubor překračuje limit 20 MB.",
    providerRateLimited:
      "Poskytovatel OCR je dočasně vytížený. Zkuste to prosím za chvíli znovu.",
  },
} as const;
