export const promptExtractorCopy = {
  en: {
    heading: "Prompt Extractor",
    upload: "Drag a manuscript PDF (up to 20 pages), or select",
    another: "Another one",
    source: "Source",
    extractedPrompts: "Extracted prompts",
    pageGroups: "PAGE GROUPS",
    copyText: "Copy text",
    copied: "Copied",
    noIllustrations: "No meaningful illustrations found.",
    processing: [
      "polishing the magnifier",
      "playing with the pen",
      "turning a page",
      "looking out of the window",
      "turning on the lamp",
      "hunching over the computer",
      "thinking about stuff",
      "procrastinating",
      "checking the horoscope",
      "taking a deep sigh",
      "thinking about things",
      "pouring a coffee",
      "doing some push-ups",
    ],
    invalidFile: "Please use a PDF file.",
    fileTooLarge: "The file is larger than the 30 MB limit.",
  },
  cs: {
    heading: "Extraktor promptů",
    upload: "Přetáhněte rukopis v PDF (max. 20 stran), nebo vyberte",
    another: "Další",
    source: "Zdroj",
    extractedPrompts: "Extrahované prompty",
    pageGroups: "SKUPINY STRAN",
    copyText: "Kopírovat text",
    copied: "Zkopírováno",
    noIllustrations: "Nebyly nalezeny žádné smysluplné ilustrace.",
    processing: [
      "leštění lupy",
      "hraní si s propiskou",
      "otáčení stránky",
      "koukání z okna",
      "rozsvěcení lampy",
      "hrbení se nad počítačem",
      "přemýšlení o všem možném",
      "prokrastinování",
      "kontrolování horoskopu",
      "hluboké povzdechnutí",
      "přemýšlení nad věcmi",
      "nalévání kávy",
      "dělání kliků",
    ],
    invalidFile: "Použijte soubor PDF.",
    fileTooLarge: "Soubor překračuje limit 30 MB.",
  },
} as const;
