export const imageGeneratorUi = {
  en: {
    code: "IMAGE / GENERATION",
    heading: "Image Generator",
    image: "IMAGE",
    empty:
      "Write one or more prompts, optionally add reference images, and generate the queue.",
    prompt: "WHAT SHOULD BE GENERATED?",
    promptPlaceholder:
      "Write one image prompt. Separate multiple prompts with an empty line.\n\nExample:\nA goose\n\nA boy\n\nA dog",
    promptCount: "prompts queued",
    importFile: "IMPORT WORD / MD / TXT",
    importHelp:
      "Drop a Word (.docx), Markdown (.md), or text (.txt) file anywhere in the app. Empty lines separate image prompts.",
    references: "REFERENCE IMAGES",
    referencesOptional: "0–3 optional",
    addImage: "ADD\nIMAGE",
    remove: "Remove",
    style: "STYLE",
    styleMatch: "Match references",
    stylePhoto: "Photorealistic composite",
    styleIllustration: "Illustration",
    style3d: "3D render",
    quality: "GENERATION QUALITY",
    qualityFast: "Low quality, faster · flux.2-klein-4b · 512 px",
    qualityFidelity: "High quality, slower · flux.2-pro · 1K",
    fidelityNote:
      "High quality costs more and follows complex prompts and reference images more reliably.",
    concurrency: "GENERATE AT A TIME",
    concurrencyOne: "1 image · sequential",
    concurrencyTwo: "2 images · faster",
    concurrencyThree: "3 images · fastest",
    generateOne: "GENERATE 1 IMAGE",
    generateMany: "GENERATE {count} IMAGES",
    stop: "STOP GENERATION",
    progress: "{complete} / {total} COMPLETE",
    queueNote:
      "Images start in prompt order. Choose up to three simultaneous images; only the first 15 prompts can be queued. You can stop the process at any time.",
    generating: "GENERATING",
    queued: "QUEUED",
    failed: "FAILED",
    stopped: "STOPPED",
    download: "DOWNLOAD",
    retry: "RETRY",
    upscale: "UPSCALE 2×",
    upscaling: "UPSCALING 2×…",
    upscaleMaximum: "MAX 2K",
    downloadAll: "DOWNLOAD ALL ↓",
    clear: "CLEAR",
    close: "Close",
    previous: "Previous image",
    next: "Next image",
    zoom: "Zoom image",
    limit: "Only the first 15 prompts will be queued.",
    promptRequired: "Write at least one image prompt.",
    importError: "The prompt file could not be read.",
    referenceError: "A reference image could not be prepared.",
    generationError: "Image generation failed.",
  },
  cs: {
    code: "OBRAZ / GENEROVÁNÍ",
    heading: "Generátor obrázků",
    image: "OBRÁZEK",
    empty:
      "Napište jedno nebo více zadání, případně přidejte referenční obrázky, a spusťte frontu.",
    prompt: "CO SE MÁ VYGENEROVAT?",
    promptPlaceholder:
      "Napište zadání pro jeden obrázek. Více zadání oddělte prázdným řádkem.\n\nPříklad:\nHusa\n\nChlapec\n\nPes",
    promptCount: "zadání ve frontě",
    importFile: "IMPORTOVAT WORD / MD / TXT",
    importHelp:
      "Přetáhněte kamkoli do aplikace soubor Word (.docx), Markdown (.md) nebo text (.txt). Prázdné řádky oddělují zadání obrázků.",
    references: "REFERENČNÍ OBRÁZKY",
    referencesOptional: "0–3 volitelné",
    addImage: "PŘIDAT\nOBRÁZEK",
    remove: "Odstranit",
    style: "STYL",
    styleMatch: "Podle referencí",
    stylePhoto: "Fotorealistická koláž",
    styleIllustration: "Ilustrace",
    style3d: "3D render",
    quality: "KVALITA GENEROVÁNÍ",
    qualityFast: "Nižší kvalita, rychlejší · flux.2-klein-4b · 512 px",
    qualityFidelity: "Vyšší kvalita, pomalejší · flux.2-pro · 1K",
    fidelityNote:
      "Vyšší kvalita stojí více a spolehlivěji následuje složitá zadání a referenční obrázky.",
    concurrency: "GENEROVAT NAJEDNOU",
    concurrencyOne: "1 obrázek · postupně",
    concurrencyTwo: "2 obrázky · rychleji",
    concurrencyThree: "3 obrázky · nejrychleji",
    generateOne: "VYGENEROVAT 1 OBRÁZEK",
    generateMany: "VYGENEROVAT {count} OBRÁZKŮ",
    stop: "ZASTAVIT GENEROVÁNÍ",
    progress: "{complete} / {total} HOTOVO",
    queueNote:
      "Obrázky se spouští v pořadí zadání. Zvolte až tři současně generované obrázky; do fronty lze zařadit pouze prvních 15 zadání. Proces můžete kdykoli zastavit.",
    generating: "GENERUJI",
    queued: "VE FRONTĚ",
    failed: "CHYBA",
    stopped: "ZASTAVENO",
    download: "STÁHNOUT",
    retry: "OPAKOVAT",
    upscale: "ZVĚTŠIT 2×",
    upscaling: "ZVĚTŠUJI 2×…",
    upscaleMaximum: "MAX 2K",
    downloadAll: "STÁHNOUT VŠE ↓",
    clear: "VYMAZAT",
    close: "Zavřít",
    previous: "Předchozí obrázek",
    next: "Další obrázek",
    zoom: "Zvětšit obrázek",
    limit: "Do fronty bude zařazeno pouze prvních 15 zadání.",
    promptRequired: "Napište alespoň jedno zadání obrázku.",
    importError: "Soubor se zadáními se nepodařilo načíst.",
    referenceError: "Referenční obrázek se nepodařilo připravit.",
    generationError: "Generování obrázku selhalo.",
  },
} as const;
