export const diagramProcessing = {
  en: [
    "checking the specimen labels",
    "peering through the microscope",
    "arranging the organelles",
    "untangling the leader lines",
    "counting the vacuoles",
    "centering the specimen",
    "sharpening the diagram pencils",
    "comparing the reference images",
    "checking what belongs where",
    "simplifying the anatomy",
    "making room for the labels",
    "giving the SVG a final polish",
  ],
  cs: [
    "kontrola popisků preparátu",
    "nahlížení do mikroskopu",
    "rovnání organel",
    "rozmotávání odkazových čar",
    "počítání vakuol",
    "centrování preparátu",
    "ořezávání tužek na schéma",
    "porovnávání referenčních obrázků",
    "kontrola, co kam patří",
    "zjednodušování anatomie",
    "uvolňování místa pro popisky",
    "závěrečné leštění SVG",
  ],
} as const;

export const diagramUi = {
  en: {
    heading: "Diagram Generator",
    subtitle:
      "Create editable biological SVGs from approved image candidates, with complete-underlay checks and separate labels.",
    label: "BIOLOGICAL DESCRIPTION",
    placeholder:
      "For example: A labelled biological diagram of an amoeba for lower-secondary students.",
    example: "Insert example",
    generate: "Generate SVG",
    generating: "Generating SVG",
    preview: "SVG PREVIEW",
    checks: "AUTOMATED CHECKS",
    downloadSvg: "Download SVG",
    downloadReport: "Download verification report (.md)",
    empty: "Nothing scarier than an empty page.",
    ready: "READY",
    planning: "BUILDING BIOLOGICAL BRIEF",
    "generating-candidates": "GENERATING IMAGE CANDIDATES",
    "candidate-selection": "CHOOSE A COMPOSITION",
    vectorizing: "RECONSTRUCTING EDITABLE SVG",
    reviewing: "RUNNING EDITORIAL REVIEW",
    complete: "EDITABLE SVG",
    brief: "BIOLOGICAL BRIEF",
    referenceMatch: "REFERENCE CATEGORY",
    candidates: "IMAGE CANDIDATES",
    candidateAlt: "Generated diagram candidate",
    vectorize: "Reconstruct editable SVG",
    review: "Review result",
    repair: "Repair once",
    reviewResult: "REVIEW",
    scores: "Scores — fidelity / editability / completeness / biology",
    failed: "The diagram workflow failed. Please retry.",
    warning:
      "Image generation is a visual aid. Review biology, labels, completeness, and rights before publication.",
    references: "REFERENCE IMAGES (OPTIONAL, MAX. 3)",
    addReference: "Add reference image",
    remove: "Remove",
    palette: "COLOR PALETTE (OPTIONAL)",
    addPalette: "Add Adobe swatches (.ase)",
    clearPalette: "Remove palette",
  },
  cs: {
    heading: "Generátor schémat",
    subtitle:
      "Vytváří upravitelná biologická SVG z vybraných obrázkových návrhů, s kontrolou úplného podkladu a samostatnými popisky.",
    label: "BIOLOGICKÝ POPIS",
    placeholder:
      "Například: Popsané biologické schéma měňavky pro žáky 2. stupně.",
    example: "Vložit příklad",
    generate: "Vytvořit SVG",
    generating: "Vytváření SVG",
    preview: "NÁHLED SVG",
    checks: "AUTOMATICKÉ KONTROLY",
    downloadSvg: "Stáhnout SVG",
    downloadReport: "Stáhnout protokol kontroly (.md)",
    empty: "Není nic děsivějšího než prázdná stránka.",
    ready: "PŘIPRAVENO",
    planning: "TVORBA BIOLOGICKÉHO ZADÁNÍ",
    "generating-candidates": "VYTVÁŘENÍ KANDIDÁTNÍCH OBRÁZKŮ",
    "candidate-selection": "VYBERTE KOMPOZICI",
    vectorizing: "REKONSTRUKCE UPRAVITELNÉHO SVG",
    reviewing: "REDAKČNÍ KONTROLA",
    complete: "UPRAVITELNÉ SVG",
    brief: "BIOLOGICKÉ ZADÁNÍ",
    referenceMatch: "KATEGORIE REFERENCE",
    candidates: "KANDIDÁTNÍ OBRÁZKY",
    candidateAlt: "Kandidátní schéma",
    vectorize: "Vytvořit upravitelné SVG",
    review: "Zkontrolovat výsledek",
    repair: "Jedna oprava",
    reviewResult: "KONTROLA",
    scores: "Skóre — věrnost / upravitelnost / úplnost / biologie",
    failed: "Pracovní postup schématu selhal. Zkuste to znovu.",
    warning:
      "Generovaný obrázek je vizuální pomůcka. Před publikací zkontrolujte biologii, popisky, úplnost a práva.",
    references: "REFERENČNÍ OBRÁZKY (VOLITELNÉ, MAX. 3)",
    addReference: "Přidat referenční obrázek",
    remove: "Odstranit",
    palette: "BAREVNÁ PALETA (VOLITELNÉ)",
    addPalette: "Přidat vzorník Adobe (.ase)",
    clearPalette: "Odstranit paletu",
  },
} as const;
