const en = {
  code: "IMAGE / CONCEPT ILLUSTRATOR",
  heading: "Concept Illustrator",
  memory: "MEMORY",
  localOnly: "Browser-local projects",
  newProject: "NEW PROJECT",
  noProjects: "Meaningful projects appear here automatically.",
  untitledProject: "Untitled article",
  openProject: "Open project",
  deleteProject: "Delete project",
  deleteConfirm: "Delete this local project and all of its image revisions?",
  updated: "Updated",
  workflow: "EDITORIAL WORKFLOW",
  stageArticle: "ARTICLE",
  stageConcepts: "3 CONCEPTS",
  stageSelect: "SELECT",
  stageGenerate: "GENERATE",
  stageRefine: "REFINE",
  stageFinal: "FINAL",
  article: "ARTICLE",
  articleHelp:
    "Paste the source text. It stays in this browser except while an AI action is running.",
  articlePlaceholder: "Paste the article or editorial brief…",
  articleRequired: "Paste an article before generating concepts.",
  generateConcepts: "GENERATE 3 CONCEPTS",
  generatingConcepts: "PLANNING CONCEPTS…",
  concepts: "THREE DIRECTIONS",
  concept: "CONCEPT",
  visual: "VISUAL",
  meaning: "MEANING",
  selectConcept: "SELECT",
  selected: "SELECTED",
  regenerateConcept: "REGENERATE CONCEPT",
  regeneratingConcept: "REGENERATING…",
  selectedDirection: "SELECTED DIRECTION",
  editBeforeGeneration:
    "Edit the chosen direction before generating one image.",
  title: "TITLE",
  generateImage: "GENERATE IMAGE",
  generatingImage: "GENERATING IMAGE…",
  selectionRequired: "Select one concept first.",
  advancedPrompt: "ADVANCED · COMPILED FINAL PROMPT",
  advancedPromptHelp:
    "Normally this is compiled automatically. Manual edits are used as written.",
  promptPlaceholder: "Compile a prompt or edit it here…",
  compilePrompt: "COMPILE PROMPT",
  compilingPrompt: "COMPILING…",
  promptManual: "Manual prompt",
  promptAutomatic: "Automatically compiled",
  activeRevision: "ACTIVE REVISION",
  noImage: "Select a concept and generate one image to begin refining.",
  revisionHistory: "REVISION HISTORY",
  revision: "REVISION",
  rootRevision: "INITIAL",
  childRevision: "EDIT",
  download: "DOWNLOAD",
  artDirection: "ART DIRECTION",
  artDirectionHelp:
    "Describe one change. A confirmed edit creates a child revision and never replaces its parent.",
  artDirectionPlaceholder:
    "E.g. move the main figure left and reduce background detail…",
  regenerate: "Regenerate",
  anotherComposition: "Try another composition",
  simplify: "Simplify",
  customEdit: "Custom edit",
  regenerateInstruction:
    "Recreate the illustration with the same concept and art direction, preserving the house style while improving clarity and finish.",
  compositionInstruction:
    "Try a distinctly different composition for the same concept while preserving its meaning and house style.",
  simplifyInstruction:
    "Simplify the composition, remove nonessential detail, and strengthen the primary visual idea.",
  customInstruction: "",
  createRevision: "CREATE NEW REVISION",
  refiningImage: "CREATING REVISION…",
  instructionRequired: "Write or choose an art-direction instruction.",
  critique: "CRITIQUE",
  critiqueHelp:
    "Run an explicit AI critique of the active revision. This is a separate paid request.",
  runCritique: "CRITIQUE IMAGE",
  critiquing: "CRITIQUING…",
  critiqueSummary: "SUMMARY",
  corrections: "CORRECTIONS",
  applyCorrections: "FILL EDIT INSTRUCTION",
  applyCorrectionsHelp:
    "Nothing is generated until you confirm with Create new revision.",
  approval: "EDITORIAL DECISION",
  pending: "Not reviewed",
  approved: "Editor approved",
  rejected: "Rejected",
  note: "OPTIONAL NOTE",
  notePlaceholder:
    "Why was this approved or rejected? Recent notes inform future concepts.",
  saveFinal: "SAVE ACTIVE AS FINAL",
  savedFinal: "FINAL REVISION",
  houseStyle: "HOUSE STYLE",
  persistentProfile: "Persistent browser-local profile",
  styleGuidance: "WRITTEN GUIDANCE",
  stylePlaceholder:
    "Palette, line, texture, tone, exclusions, publication rules…",
  aspectRatio: "ASPECT RATIO",
  references: "REFERENCE ILLUSTRATIONS",
  referencesHelp:
    "Up to 3 · PNG, JPEG, or WebP · source max 30 MB · saved as JPEG max 1600 px",
  addReference: "ADD REFERENCE",
  removeReference: "Remove reference",
  referenceError: "The reference illustration could not be prepared.",
  referenceTypeError: "Use a PNG, JPEG, or WebP image.",
  referenceSizeError: "The source image is larger than 30 MB.",
  referenceLimitError: "The house style can contain at most 3 references.",
  localStorageNote:
    "Projects and style references stay in this browser. Clearing browser storage removes them.",
  planningError: "Concept planning failed.",
  regenerationError: "Concept regeneration failed.",
  compileError: "Prompt compilation failed.",
  generationError: "Image generation failed.",
  refinementError: "Image refinement failed.",
  critiqueError: "Image critique failed.",
  invalidConcepts:
    "The planner did not return exactly three complete concepts.",
  invalidResponse: "The service returned an incomplete response.",
  memoryError:
    "Local memory could not be updated. Storage may be unavailable or full.",
  busy: "Another AI request is already running.",
} as const;

type CopyShape = { [Key in keyof typeof en]: string };

const cs = {
  code: "OBRAZ / KONCEPT ILUSTRACE",
  heading: "Koncept ilustrace",
  memory: "PAMĚŤ",
  localOnly: "Projekty pouze v prohlížeči",
  newProject: "NOVÝ PROJEKT",
  noProjects: "Smysluplné projekty se zde ukládají automaticky.",
  untitledProject: "Článek bez názvu",
  openProject: "Otevřít projekt",
  deleteProject: "Smazat projekt",
  deleteConfirm: "Smazat tento místní projekt včetně všech revizí obrázku?",
  updated: "Upraveno",
  workflow: "REDAKČNÍ POSTUP",
  stageArticle: "ČLÁNEK",
  stageConcepts: "3 KONCEPTY",
  stageSelect: "VÝBĚR",
  stageGenerate: "GENEROVÁNÍ",
  stageRefine: "ÚPRAVY",
  stageFinal: "FINÁLE",
  article: "ČLÁNEK",
  articleHelp:
    "Vložte zdrojový text. Zůstává v tomto prohlížeči kromě okamžiku, kdy probíhá AI akce.",
  articlePlaceholder: "Vložte článek nebo redakční zadání…",
  articleRequired: "Před generováním konceptů vložte článek.",
  generateConcepts: "VYGENEROVAT 3 KONCEPTY",
  generatingConcepts: "PLÁNUJI KONCEPTY…",
  concepts: "TŘI SMĚRY",
  concept: "KONCEPT",
  visual: "VIZUÁL",
  meaning: "VÝZNAM",
  selectConcept: "VYBRAT",
  selected: "VYBRÁNO",
  regenerateConcept: "PŘEGENEROVAT KONCEPT",
  regeneratingConcept: "PŘEGENEROVÁVÁM…",
  selectedDirection: "VYBRANÝ SMĚR",
  editBeforeGeneration:
    "Před vygenerováním jednoho obrázku můžete vybraný směr upravit.",
  title: "NÁZEV",
  generateImage: "VYGENEROVAT OBRÁZEK",
  generatingImage: "GENERUJI OBRÁZEK…",
  selectionRequired: "Nejprve vyberte jeden koncept.",
  advancedPrompt: "POKROČILÉ · FINÁLNÍ SESTAVENÝ PROMPT",
  advancedPromptHelp:
    "Běžně se sestaví automaticky. Ruční úpravy se použijí přesně tak, jak jsou napsané.",
  promptPlaceholder: "Sestavte prompt nebo jej zde upravte…",
  compilePrompt: "SESTAVIT PROMPT",
  compilingPrompt: "SESTAVUJI…",
  promptManual: "Ručně upravený prompt",
  promptAutomatic: "Automaticky sestaveno",
  activeRevision: "AKTIVNÍ REVIZE",
  noImage:
    "Vyberte koncept a vygenerujte jeden obrázek, poté jej můžete upravovat.",
  revisionHistory: "HISTORIE REVIZÍ",
  revision: "REVIZE",
  rootRevision: "PRVNÍ",
  childRevision: "ÚPRAVA",
  download: "STÁHNOUT",
  artDirection: "VÝTVARNÉ SMĚŘOVÁNÍ",
  artDirectionHelp:
    "Popište jednu změnu. Potvrzená úprava vytvoří novou podřízenou revizi a rodiče nikdy nepřepíše.",
  artDirectionPlaceholder:
    "Např. přesuň hlavní postavu doleva a omez detaily pozadí…",
  regenerate: "Přegenerovat",
  anotherComposition: "Zkusit jinou kompozici",
  simplify: "Zjednodušit",
  customEdit: "Vlastní úprava",
  regenerateInstruction:
    "Vytvoř ilustraci znovu se stejným konceptem a výtvarným směrem, zachovej styl domu a zlepši čitelnost i provedení.",
  compositionInstruction:
    "Zkus výrazně odlišnou kompozici stejného konceptu, ale zachovej jeho význam a styl domu.",
  simplifyInstruction:
    "Zjednoduš kompozici, odstraň nepodstatné detaily a posil hlavní vizuální myšlenku.",
  customInstruction: "",
  createRevision: "VYTVOŘIT NOVOU REVIZI",
  refiningImage: "VYTVÁŘÍM REVIZI…",
  instructionRequired: "Napište nebo zvolte pokyn k výtvarné úpravě.",
  critique: "KRITIKA",
  critiqueHelp:
    "Spusťte výslovnou AI kritiku aktivní revize. Jde o samostatný placený požadavek.",
  runCritique: "ZKRITIZOVAT OBRÁZEK",
  critiquing: "HODNOTÍM…",
  critiqueSummary: "SHRNUTÍ",
  corrections: "OPRAVY",
  applyCorrections: "VLOŽIT POKYN K ÚPRAVĚ",
  applyCorrectionsHelp:
    "Nic se nevygeneruje, dokud nepotvrdíte tlačítkem Vytvořit novou revizi.",
  approval: "REDAKČNÍ ROZHODNUTÍ",
  pending: "Nehodnoceno",
  approved: "Schváleno redaktorem",
  rejected: "Zamítnuto",
  note: "VOLITELNÁ POZNÁMKA",
  notePlaceholder:
    "Proč bylo dílo schváleno či zamítnuto? Nedávné poznámky ovlivní další koncepty.",
  saveFinal: "ULOŽIT AKTIVNÍ JAKO FINÁLNÍ",
  savedFinal: "FINÁLNÍ REVIZE",
  houseStyle: "STYL DOMU",
  persistentProfile: "Trvalý profil v tomto prohlížeči",
  styleGuidance: "PÍSEMNÉ POKYNY",
  stylePlaceholder: "Paleta, linka, textura, tón, zákazy, pravidla publikace…",
  aspectRatio: "POMĚR STRAN",
  references: "REFERENČNÍ ILUSTRACE",
  referencesHelp:
    "Až 3 · PNG, JPEG nebo WebP · zdroj max. 30 MB · ukládá se jako JPEG max. 1600 px",
  addReference: "PŘIDAT REFERENCI",
  removeReference: "Odstranit referenci",
  referenceError: "Referenční ilustraci se nepodařilo připravit.",
  referenceTypeError: "Použijte obrázek PNG, JPEG nebo WebP.",
  referenceSizeError: "Zdrojový obrázek je větší než 30 MB.",
  referenceLimitError: "Styl domu může obsahovat nejvýše 3 reference.",
  localStorageNote:
    "Projekty a stylové reference zůstávají v tomto prohlížeči. Vymazání dat prohlížeče je odstraní.",
  planningError: "Plánování konceptů selhalo.",
  regenerationError: "Přegenerování konceptu selhalo.",
  compileError: "Sestavení promptu selhalo.",
  generationError: "Generování obrázku selhalo.",
  refinementError: "Úprava obrázku selhala.",
  critiqueError: "Kritika obrázku selhala.",
  invalidConcepts: "Plánovač nevrátil přesně tři úplné koncepty.",
  invalidResponse: "Služba vrátila neúplnou odpověď.",
  memoryError:
    "Místní paměť se nepodařilo aktualizovat. Úložiště může být nedostupné nebo plné.",
  busy: "Právě probíhá jiný AI požadavek.",
} satisfies CopyShape;

export const conceptIllustratorUi = { en, cs } as const;
