export const graphProcessing = {
  en: ["checking every supplied number", "reading the source line twice", "choosing sensible axes", "measuring the longest label", "counting the data points", "lining up the tick marks", "looking for a missing unit", "balancing the chart margins", "drawing the bars with a ruler", "joining the points", "checking the legend", "giving the SVG a final polish"],
  cs: ["kontrola každého zadaného čísla", "dvojí čtení zdroje", "volba rozumných os", "měření nejdelšího popisku", "počítání datových bodů", "rovnání značek na ose", "hledání chybějící jednotky", "vyvažování okrajů grafu", "rýsování sloupců", "spojování bodů", "kontrola legendy", "závěrečné leštění SVG"],
} as const;

export const graphUi = {
  en: { subtitle: "Create source-backed SVG charts. Specifications are validated and coordinates are rendered by code.", badge: "VERIFIED PIPELINE", label: "FACTS, VALUES AND SOURCES", placeholder: "Example: Make a line chart titled …\n2022: 18.4\n2023: 21.1\n2024: 23.7\nUnit: percent\nSource: Statistical office, https://…", generate: "Generate SVG (about 30 seconds)", generating: "Generating SVG", preview: "SVG PREVIEW", checks: "AUTOMATED CHECKS", downloadSvg: "Download SVG", downloadReport: "Download verification report (.md)", empty: "Nothing scarier than an empty page.", warning: "Charts validate supplied data.", example: "Insert example", palette: "COLOR PALETTE (OPTIONAL)", addPalette: "Add Adobe swatches (.ase)", clearPalette: "Remove palette", paletteFileError: "Choose an Adobe Swatch Exchange (.ase) file up to 2 MB.", paletteReadError: "Could not read the ASE palette." },
  cs: { subtitle: "Vytváří zdrojované SVG grafy. Specifikace ověří a souřadnice vykreslí kód.", badge: "OVĚŘOVANÝ POSTUP", label: "FAKTA, HODNOTY A ZDROJE", placeholder: "Příklad: Vytvoř spojnicový graf s názvem …\n2022: 18,4\n2023: 21,1\n2024: 23,7\nJednotka: procenta\nZdroj: Statistický úřad, https://…", generate: "Vytvořit SVG (asi 30 sekund)", generating: "Vytváření SVG", preview: "NÁHLED SVG", checks: "AUTOMATICKÉ KONTROLY", downloadSvg: "Stáhnout SVG", downloadReport: "Stáhnout protokol kontroly (.md)", empty: "Není nic děsivějšího než prázdná stránka.", warning: "Grafy ověřují dodaná data.", example: "Vložit příklad", palette: "BAREVNÁ PALETA (VOLITELNÉ)", addPalette: "Přidat vzorník Adobe (.ase)", clearPalette: "Odstranit paletu", paletteFileError: "Vyberte soubor Adobe Swatch Exchange (.ase) o velikosti nejvýše 2 MB.", paletteReadError: "Paletu ASE se nepodařilo načíst." },
} as const;
