/* Experimental Solutions Importer for direct PDF-coordinate placement.
 *
 * Advanced is intentionally not implemented in this experimental copy.
 * Simple is the failsafe path: one enabled, valid text operation becomes one
 * text frame on the SOLUTIONS layer.
 */

#target "InDesign"

(function () {
    var TITLE = "Import Solutions";
    var TEST_JSON_PATH = $.global.__SOLUTIONS_JSON_PATH__ || "";
    var MODE_OVERRIDE = String($.global.__SOLUTIONS_IMPORT_MODE__ || "").toLowerCase();
    var LAYER_NAME = "SOLUTIONS";
    var TEXT_STYLE_NAME = "Solutions";
    var SWATCH_NAME = "SOLUTIONS";
    var SIMPLE_GENERATED_PREFIX = "Solutions Simple:";
    var AUTOMATED = $.global.__SOLUTIONS_IMPORTER_AUTOMATED__ === true ||
        $.global.__SOLUTIONS_BETA_AUTOMATED__ === true ||
        $.global.__SOLUTIONS_SIMPLE_AUTOMATED__ === true;

    if (!app.documents.length) {
        notify("Open the matching InDesign chapter before running this script.");
        return;
    }

    app.doScript(run, ScriptLanguage.JAVASCRIPT, undefined,
        UndoModes.ENTIRE_SCRIPT, TITLE);

    function run() {
        var jsonFile = TEST_JSON_PATH ? File(TEST_JSON_PATH) : null;
        if (!jsonFile || !jsonFile.exists) {
            jsonFile = File.openDialog("Choose Solutions Importer JSON", "JSON:*.json");
        }
        if (!jsonFile) return;

        var data = readJson(jsonFile);
        if (!data) return;
        if (data.format !== "indesign-solutions-v2" || !data.pages ||
                typeof data.pages.length !== "number") {
            notify("This is not Solutions Importer JSON.");
            return;
        }

        var doc = app.activeDocument;
        if (data.pages.length !== doc.pages.length) {
            notify("Page-count mismatch.\n\nJSON: " + data.pages.length +
                "\nInDesign: " + doc.pages.length);
            return;
        }
        if (!confirmPageNames(doc, data)) return;

        var mode = chooseImportMode();
        if (!mode) return;
        if (mode === "advanced") {
            notify("Coming soon!");
            return;
        }

        runSimpleImport(doc, data);
    }

    function chooseImportMode() {
        if (MODE_OVERRIDE === "advanced" || MODE_OVERRIDE === "simple") {
            return MODE_OVERRIDE;
        }
        if (AUTOMATED) {
            throw new Error("Set __SOLUTIONS_IMPORT_MODE__ to advanced or simple for automated use.");
        }

        var dialog = new Window("dialog", "Import Solutions");
        dialog.orientation = "column";
        dialog.alignChildren = "fill";

        var introduction = dialog.add(
            "statictext", undefined,
            "Choose how the reviewed solutions should be placed:",
            {multiline: true}
        );
        introduction.preferredSize.width = 440;

        var choices = dialog.add("panel", undefined, "Placement mode");
        choices.orientation = "column";
        choices.alignChildren = "left";
        choices.margins = 16;

        var advanced = choices.add(
            "radiobutton", undefined,
            "Advanced: use tables, answer boxes, and continuation alignment"
        );
        advanced.value = true;

        var simple = choices.add(
            "radiobutton", undefined,
            "Simple: place text directly at its PDF coordinates"
        );

        var warning = dialog.add(
            "statictext", undefined,
            "Advanced is not available in this experimental copy.\n" +
            "Simple replaces only frames generated by an earlier Simple import.",
            {multiline: true}
        );
        warning.preferredSize.width = 440;

        var buttons = dialog.add("group");
        buttons.alignment = "right";
        buttons.add("button", undefined, "Cancel", {name: "cancel"});
        buttons.add("button", undefined, "Import", {name: "ok"});

        if (dialog.show() !== 1) return null;
        return simple.value ? "simple" : "advanced";
    }

    function runSimpleImport(doc, data) {
        var layer = ensureLayer(doc);
        var oldItems = collectGeneratedItems(layer);
        var swatch = ensureSolutionSwatch(doc);
        var typography = readTypography(data);
        var font = resolveFont(typography.fontFamily);
        if (!font) {
            notify('The selected font "' + typography.fontFamily + '" is not installed.');
            return;
        }
        var style = ensureParagraphStyle(doc, TEXT_STYLE_NAME, swatch, font,
            typography.pointSize);
        var noneCharacterStyle = getNoneCharacterStyle(doc);

        var oldH = doc.viewPreferences.horizontalMeasurementUnits;
        var oldV = doc.viewPreferences.verticalMeasurementUnits;
        var oldOrigin = doc.viewPreferences.rulerOrigin;
        var oldLayerVisible = layer.visible;
        var oldLayerLocked = layer.locked;
        var createdItems = [];
        var progressPalette = null;
        var placed = 0;
        var skipped = 0;
        var processed = 0;
        var total = countEnabledOperations(data);

        try {
            doc.viewPreferences.horizontalMeasurementUnits = MeasurementUnits.POINTS;
            doc.viewPreferences.verticalMeasurementUnits = MeasurementUnits.POINTS;
            doc.viewPreferences.rulerOrigin = RulerOrigin.PAGE_ORIGIN;

            progressPalette = createProgressPalette(total);
            layer.visible = true;
            layer.locked = false;
            updateProgress(progressPalette, 0, total, "Preparing Simple import...");

            for (var pageIndex = 0; pageIndex < data.pages.length; pageIndex++) {
                var page = doc.pages[pageIndex];
                var pageData = data.pages[pageIndex];
                var pdfWidth = Number(pageData.width);
                var pdfHeight = Number(pageData.height);
                if (!isFinite(pdfWidth) || !isFinite(pdfHeight) ||
                        pdfWidth <= 0 || pdfHeight <= 0) {
                    throw new Error("Invalid PDF dimensions on page " + (pageIndex + 1) + ".");
                }

                var pageWidth = page.bounds[3] - page.bounds[1];
                var pageHeight = page.bounds[2] - page.bounds[0];
                var scaleX = pageWidth / pdfWidth;
                var scaleY = pageHeight / pdfHeight;
                var operations = pageData.operations || [];

                for (var operationIndex = 0; operationIndex < operations.length; operationIndex++) {
                    var operation = operations[operationIndex];
                    if (!isEnabledOperation(operation)) continue;

                    processed++;
                    updateProgress(
                        progressPalette, processed, total,
                        "Operation " + processed + " of " + total +
                        (operation.kind === "text" ? ": placing text" : ": skipping non-text")
                    );

                    if (!isValidTextOperation(operation)) {
                        skipped++;
                        continue;
                    }

                    var bounds = scaledBounds(operation.bounds, scaleX, scaleY);
                    bounds = constrainBounds(bounds, pageWidth, pageHeight,
                        typography.pointSize);
                    var frame = page.textFrames.add(layer, undefined, undefined, {
                        geometricBounds: bounds,
                        contents: normalizeText(operation.text)
                    });
                    createdItems.push(frame);
                    frame.label = SIMPLE_GENERATED_PREFIX +
                        (operation.id !== undefined ? operation.id : operationIndex);
                    clearFrameAppearance(frame, doc);
                    clearFrameInsets(frame);
                    frame.textFramePreferences.firstBaselineOffset =
                        FirstBaseline.ASCENT_OFFSET;
                    frame.parentStory.paragraphs[0].appliedParagraphStyle = style;
                    frame.parentStory.paragraphs[0].justification = Justification.LEFT_ALIGN;
                    applyNoneCharacterStyle(frame.parentStory.texts[0], noneCharacterStyle);
                    placed++;
                }
            }

            var removalErrors = removeItems(oldItems);
            if (removalErrors.length) {
                throw new Error("Could not remove previous Simple-import items.\n" +
                    removalErrors.join("\n"));
            }
            updateProgress(progressPalette, processed, total,
                "Simple import complete.");
        } catch (error) {
            var cleanupErrors = removeItems(createdItems);
            var failure = "Import failed. Previous Simple-import items were kept.\n\n" +
                error;
            if (cleanupErrors.length) {
                failure += "\n\nSome new items could not be removed:\n" +
                    cleanupErrors.join("\n");
            }
            if (AUTOMATED) throw new Error(failure);
            alert(failure, TITLE);
            return;
        } finally {
            closeProgressPalette(progressPalette);
            doc.viewPreferences.horizontalMeasurementUnits = oldH;
            doc.viewPreferences.verticalMeasurementUnits = oldV;
            doc.viewPreferences.rulerOrigin = oldOrigin;
            try {
                layer.visible = oldLayerVisible;
            } catch (visibilityError) {
                $.writeln("Solutions Simple warning: could not restore layer visibility: " +
                    visibilityError);
            }
            try {
                layer.locked = oldLayerLocked;
            } catch (lockError) {
                $.writeln("Solutions Simple warning: could not restore layer lock: " +
                    lockError);
            }
        }

        if (!AUTOMATED) {
            alert("Simple Solutions import completed.\n\nText frames placed: " + placed +
                "\nNon-text or invalid operations skipped: " + skipped +
                "\n\nCheck the SOLUTIONS layer page by page.", TITLE);
        }
    }

    function readJson(file) {
        file.encoding = "UTF-8";
        if (!file.open("r")) {
            notify("Could not open: " + file.fsName);
            return null;
        }
        var raw = file.read().replace(/^\uFEFF/, "");
        file.close();
        try {
            if (typeof JSON !== "undefined" && JSON.parse) return JSON.parse(raw);
            return eval("(" + raw + ")");
        } catch (error) {
            notify("Could not parse the selected JSON.\n\n" + error);
            return null;
        }
    }

    function notify(message) {
        if (AUTOMATED) throw new Error(message);
        alert(message, TITLE);
    }

    function ensureLayer(doc) {
        var layer = doc.layers.itemByName(LAYER_NAME);
        if (!layer.isValid) layer = doc.layers.add({name: LAYER_NAME});
        return layer;
    }

    function ensureSolutionSwatch(doc) {
        var swatch = doc.colors.itemByName(SWATCH_NAME);
        if (!swatch.isValid) {
            swatch = doc.colors.add({
                name: SWATCH_NAME,
                model: ColorModel.PROCESS,
                space: ColorSpace.CMYK,
                colorValue: [100, 73, 0, 0]
            });
        }
        return swatch;
    }

    function readTypography(data) {
        var allowed = {"Arial": true, "Noto Sans": true, "Times New Roman": true};
        var family = data.settings && allowed[data.settings.font_family]
            ? data.settings.font_family : "Noto Sans";
        var size = data.settings ? Number(data.settings.point_size) : 14;
        if (size !== 12 && size !== 14) size = 14;
        return {fontFamily: family, pointSize: size};
    }

    function resolveFont(family) {
        var font;
        try {
            font = app.fonts.itemByName(family + "\tRegular");
            if (font.isValid) return font;
        } catch (lookupError) {
            $.writeln("Solutions Simple warning: direct font lookup failed: " +
                lookupError);
        }
        for (var index = 0; index < app.fonts.length; index++) {
            try {
                font = app.fonts[index];
                if (String(font.fontFamily) === family &&
                        String(font.fontStyleName).toLowerCase() === "regular") return font;
            } catch (fontError) {
                $.writeln("Solutions Simple warning: could not inspect font " + index + ": " +
                    fontError);
            }
        }
        return null;
    }

    function ensureParagraphStyle(doc, name, swatch, font, pointSize) {
        var style = doc.paragraphStyles.itemByName(name);
        if (!style.isValid) style = doc.paragraphStyles.add({name: name});
        style.appliedFont = font;
        try {
            style.fontStyle = font.fontStyleName;
        } catch (styleFontError) {
            $.writeln("Solutions Simple warning: could not set font style: " +
                styleFontError);
        }
        style.pointSize = pointSize;
        style.leading = pointSize;
        style.fillColor = swatch;
        style.spaceBefore = 0;
        style.spaceAfter = 0;
        style.justification = Justification.LEFT_ALIGN;
        return style;
    }

    function getNoneCharacterStyle(doc) {
        var style = doc.characterStyles.itemByName("$ID/[None]");
        if (style.isValid) return style;
        style = doc.characterStyles.itemByName("[None]");
        if (style.isValid) return style;
        return null;
    }

    function applyNoneCharacterStyle(text, style) {
        if (!style || !style.isValid || !text) return;
        try {
            text.appliedCharacterStyle = style;
        } catch (error) {
            $.writeln("Solutions Simple warning: could not apply [None] character style: " +
                error);
        }
    }

    function confirmPageNames(doc, data) {
        if (!data.document || !data.document.page_names) return true;
        var mismatches = [];
        for (var index = 0; index < doc.pages.length; index++) {
            if (String(doc.pages[index].name) !== String(data.document.page_names[index])) {
                mismatches.push((index + 1) + ": " + doc.pages[index].name +
                    " / " + data.document.page_names[index]);
                if (mismatches.length === 5) break;
            }
        }
        if (!mismatches.length) return true;
        return confirm(
            "Some InDesign page names differ from the IDML used for extraction.\n\n" +
            mismatches.join("\n") + "\n\nContinue using PDF page order?"
        );
    }

    function isEnabledOperation(operation) {
        return !!operation && operation.enabled !== false;
    }

    function isValidTextOperation(operation) {
        if (!isEnabledOperation(operation) || operation.kind !== "text") return false;
        if (!normalizeText(operation.text)) return false;
        if (!operation.bounds || operation.bounds.length !== 4) return false;
        for (var index = 0; index < operation.bounds.length; index++) {
            if (!isFinite(Number(operation.bounds[index]))) return false;
        }
        return true;
    }

    function countEnabledOperations(data) {
        var count = 0;
        for (var pageIndex = 0; pageIndex < data.pages.length; pageIndex++) {
            var operations = data.pages[pageIndex].operations || [];
            for (var operationIndex = 0; operationIndex < operations.length; operationIndex++) {
                if (isEnabledOperation(operations[operationIndex])) count++;
            }
        }
        return count;
    }

    function collectGeneratedItems(layer) {
        var items = layer.allPageItems;
        var result = [];
        for (var index = 0; index < items.length; index++) {
            try {
                if (String(items[index].label).indexOf(SIMPLE_GENERATED_PREFIX) === 0) {
                    result.push(items[index]);
                }
            } catch (labelError) {
                $.writeln("Solutions Simple warning: could not inspect item label: " +
                    labelError);
            }
        }
        return result;
    }

    function removeItems(items) {
        var errors = [];
        for (var index = items.length - 1; index >= 0; index--) {
            try {
                if (items[index].isValid) items[index].remove();
            } catch (error) {
                errors.push("Item " + index + ": " + error);
            }
        }
        return errors;
    }

    function getNoneSwatch(doc) {
        var names = ["$ID/None", "None"];
        var errors = [];
        for (var index = 0; index < names.length; index++) {
            try {
                var none = doc.swatches.itemByName(names[index]);
                if (none.isValid) return none;
                errors.push(names[index] + " is not valid");
            } catch (error) {
                errors.push(names[index] + ": " + error);
            }
        }
        try {
            var firstSwatch = doc.swatches[0];
            if (firstSwatch.isValid) return firstSwatch;
        } catch (fallbackError) {
            errors.push("first swatch: " + fallbackError);
        }
        throw new Error("Could not find the InDesign None swatch. " +
            errors.join("; "));
    }

    function clearFrameAppearance(frame, doc) {
        var none = getNoneSwatch(doc);
        var errors = [];
        try {
            frame.fillColor = none;
        } catch (fillError) {
            errors.push("fill: " + fillError);
        }
        try {
            frame.strokeColor = none;
        } catch (strokeError) {
            errors.push("stroke color: " + strokeError);
        }
        try {
            frame.strokeWeight = 0;
        } catch (weightError) {
            errors.push("stroke weight: " + weightError);
        }
        if (errors.length) {
            throw new Error("Could not clear generated frame appearance.\n" +
                errors.join("\n"));
        }
    }

    function clearFrameInsets(frame) {
        try {
            frame.textFramePreferences.insetSpacing = [0, 0, 0, 0];
        } catch (insetError) {
            throw new Error("Could not set zero text-frame insets: " + insetError);
        }
    }

    function createProgressPalette(total) {
        var palette = new Window("palette", TITLE);
        palette.orientation = "column";
        palette.alignChildren = "fill";
        palette.margins = 16;
        palette.statusText = palette.add("statictext", undefined,
            "Preparing Simple import...");
        palette.statusText.preferredSize.width = 360;
        palette.progressBar = palette.add("progressbar", undefined, 0,
            Math.max(1, total));
        palette.progressBar.preferredSize.width = 360;
        palette.show();
        return palette;
    }

    function updateProgress(palette, value, total, status) {
        if (!palette) return;
        palette.progressBar.value = value;
        palette.statusText.text = status;
        try {
            palette.update();
        } catch (updateError) {
            $.writeln("Solutions Simple warning: could not redraw progress palette: " +
                updateError);
        }
        try {
            app.processTasks();
        } catch (taskError) {
            $.writeln("Solutions Simple warning: could not process palette events: " +
                taskError);
        }
    }

    function closeProgressPalette(palette) {
        if (!palette) return;
        try {
            palette.close();
        } catch (closeError) {
            $.writeln("Solutions Simple warning: could not close progress palette: " +
                closeError);
        }
    }

    function scaledBounds(bounds, scaleX, scaleY) {
        return [
            Number(bounds[0]) * scaleY,
            Number(bounds[1]) * scaleX,
            Number(bounds[2]) * scaleY,
            Number(bounds[3]) * scaleX
        ];
    }

    function constrainBounds(bounds, pageWidth, pageHeight, pointSize) {
        var minimumHeight = Math.min(pageHeight, Math.max(1, pointSize + 2));
        var minimumWidth = Math.min(pageWidth, 12);
        bounds[0] = clamp(bounds[0], 0,
            Math.max(0, pageHeight - minimumHeight));
        bounds[1] = clamp(bounds[1], 0,
            Math.max(0, pageWidth - minimumWidth));
        bounds[2] = clamp(Math.max(bounds[2], bounds[0] + minimumHeight),
            bounds[0] + minimumHeight, pageHeight);
        bounds[3] = clamp(Math.max(bounds[3], bounds[1] + minimumWidth),
            bounds[1] + minimumWidth, pageWidth);
        return bounds;
    }

    function clamp(value, minimum, maximum) {
        return Math.min(maximum, Math.max(minimum, value));
    }

    function normalizeText(text) {
        return String(text || "").replace(/[ \t]+/g, " ").replace(/^\s+|\s+$/g, "");
    }
})();
