export const indexCreatorCopy = {
  en: {
    heading: "Index Creator",
    upload: "Drag PDF, or click here to select file",
    another: "Another one",
    wordList: "One index word or phrase per line",
    createIndex: "Create index",
    indexOutput: "Index output",
    indexLegend: "Term [Tab] Best match [Tab] All other matches",
    source: "Source",
    copyText: "Copy text",
    copied: "Copied",
    pdfPage: "PDF page",
    printedPage: "Printed page",
    pageMapping: "Page-number anchor",
    localExtraction: "The PDF text stays in this browser",
    processing: [
      "communicating",
      "calculating",
      "slicing bread",
      "spreading butter",
      "packing lunch",
      "looking up the way to the library",
      "waiting for the tram",
      "looking for a place to sit",
      "2+2=???",
      "hm…",
      "looking for a bench in the park",
      "consuming sandwich",
      "staring into space",
      "looking at trees",
    ],
    invalidFile: "Please use a PDF file.",
  },
  cs: {
    heading: "Tvůrce rejstříku",
    upload: "Přetáhněte PDF nebo klikněte pro výběr",
    another: "Další",
    wordList: "Jedno slovo nebo slovní spojení na řádek",
    createIndex: "Vytvořit rejstřík",
    indexOutput: "Výstup rejstříku",
    indexLegend: "Heslo [Tab] Nejlepší shoda [Tab] Všechny ostatní shody",
    source: "Zdroj",
    copyText: "Kopírovat text",
    copied: "Zkopírováno",
    pdfPage: "Strana PDF",
    printedPage: "Tištěná strana",
    pageMapping: "Kotva číslování stran",
    localExtraction: "Text PDF zůstává v tomto prohlížeči",
    processing: [
      "komunikace",
      "kalkulace",
      "krájení chleba",
      "mazání chleba máslem",
      "balení svačiny",
      "vyhledávání cesty do knihovny",
      "čekání na tramvaj",
      "hledání místa k sezení",
      "2+2=???",
      "hm…",
      "hledání lavičky v parku",
      "konzumace svačiny",
      "koukání do blba",
      "koukání na stromy",
    ],
    invalidFile: "Použijte soubor PDF.",
  },
} as const;
