export const indexCreatorCopy = {
  en: {
    heading: "Index Creator",
    upload: "Drag PDF, or click here to select file",
    another: "Another",
    wordList: "One index word or phrase per line",
    createIndex: "Create index",
    indexOutput: "Index output",
    indexLegend: "Accepted pages; possible pages can be added or removed",
    source: "Source",
    emptySource: "Drop file here, paste, or click to select",
    copyText: "Copy text",
    copied: "Copied",
    pdfPage: "PDF page",
    printedPage: "Printed page",
    possible: "Possible",
    matchDetails: "Match details",
    matchedForms: "Matched forms",
    reasonLabels: {
      "exact-term": "exact submitted term",
      "complete-inflection": "complete grammatical form",
      "formatting-variant": "formatting variant",
      "spelling-tolerance": "small spelling tolerance",
      "near-page-heading": "near the page heading",
      "substantial-prose": "substantial explanatory text",
      "repeated-treatment": "repeated on the page",
      "question-heavy": "question-heavy context",
      "caption-like": "caption-like context",
      "list-like": "list-like context",
      "cross-reference-only": "cross-reference context",
      "contextual-short-name": "shortened name near a full match",
      "stem-match": "word-stem match",
      "phrase-proximity": "phrase components found nearby",
      "diacritic-variant": "diacritic-normalized match",
      "fuzzy-token": "approximate spelling match",
      "adjacent-page": "neighbouring page of a strong match",
      "manual-review-required": "manual review recommended",
    },
    sourcePage: "Source match on PDF page",
    matchKindLabels: {
      "exact-term": "exact term",
      "complete-inflection": "complete form",
      "formatting-variant": "formatting variant",
      "spelling-tolerance": "spelling tolerance",
      "contextual-short-name": "shortened name",
      "stem-match": "word stem",
      "phrase-proximity": "nearby phrase",
      "diacritic-variant": "diacritic variant",
      "fuzzy-token": "approximate spelling",
      "adjacent-page": "neighbouring page",
    },
    acceptPage: "Accept page",
    demotePage: "Move to possible pages",
    pageMapping: "Page-number anchor",
    localExtraction: "The PDF text stays in this browser",
    processing: [
      "communicating",
      "calculating",
      "slicing bread",
      "spreading butter",
      "packing lunch",
      "looking up the way to the library",
      "waiting for the tram",
      "looking for a place to sit",
      "2+2=???",
      "hm…",
      "looking for a bench in the park",
      "consuming sandwich",
      "staring into space",
      "looking at trees",
    ],
    invalidFile: "Please use a PDF file.",
  },
  cs: {
    heading: "Tvůrce rejstříku",
    upload: "Přetáhněte PDF nebo klikněte pro výběr",
    another: "Další",
    wordList: "Jedno slovo nebo slovní spojení na řádek",
    createIndex: "Vytvořit rejstřík",
    indexOutput: "Výstup rejstříku",
    indexLegend: "Přijaté strany; možné strany lze přidat nebo odebrat",
    source: "Zdroj",
    emptySource: "Přetáhněte soubor sem, vložte ho nebo klikněte pro výběr",
    copyText: "Kopírovat text",
    copied: "Zkopírováno",
    pdfPage: "Strana PDF",
    printedPage: "Tištěná strana",
    possible: "Možné",
    matchDetails: "Podrobnosti shody",
    matchedForms: "Nalezené tvary",
    reasonLabels: {
      "exact-term": "přesný zadaný termín",
      "complete-inflection": "úplný gramatický tvar",
      "formatting-variant": "formátová varianta",
      "spelling-tolerance": "malá pravopisná tolerance",
      "near-page-heading": "blízko nadpisu strany",
      "substantial-prose": "rozsáhlejší vysvětlující text",
      "repeated-treatment": "opakovaný výskyt na straně",
      "question-heavy": "kontext s mnoha otázkami",
      "caption-like": "kontext podobný popisku",
      "list-like": "kontext podobný seznamu",
      "cross-reference-only": "kontext pouze s odkazem",
      "contextual-short-name": "zkrácené jméno blízko úplné shody",
      "stem-match": "shoda podle slovního základu",
      "phrase-proximity": "části fráze nalezeny blízko sebe",
      "diacritic-variant": "shoda bez ohledu na diakritiku",
      "fuzzy-token": "přibližná pravopisná shoda",
      "adjacent-page": "sousední strana silné shody",
      "manual-review-required": "doporučena ruční kontrola",
    },
    sourcePage: "Zdrojová shoda na straně PDF",
    matchKindLabels: {
      "exact-term": "přesný termín",
      "complete-inflection": "úplný tvar",
      "formatting-variant": "formátová varianta",
      "spelling-tolerance": "pravopisná tolerance",
      "contextual-short-name": "zkrácené jméno",
      "stem-match": "slovní základ",
      "phrase-proximity": "blízká fráze",
      "diacritic-variant": "varianta diakritiky",
      "fuzzy-token": "přibližný pravopis",
      "adjacent-page": "sousední strana",
    },
    acceptPage: "Přijmout stranu",
    demotePage: "Přesunout mezi možné strany",
    pageMapping: "Kotva číslování stran",
    localExtraction: "Text PDF zůstává v tomto prohlížeči",
    processing: [
      "komunikace",
      "kalkulace",
      "krájení chleba",
      "mazání chleba máslem",
      "balení svačiny",
      "vyhledávání cesty do knihovny",
      "čekání na tramvaj",
      "hledání místa k sezení",
      "2+2=???",
      "hm…",
      "hledání lavičky v parku",
      "konzumace svačiny",
      "koukání do blba",
      "koukání na stromy",
    ],
    invalidFile: "Použijte soubor PDF.",
  },
} as const;
